function metrics=r3b_recontact_metrics(result)
%R3B_RECONTACT_METRICS Contact-margin and return-policy diagnostics.

dt=result.config.dt;active=result.active_contacts>0;
controlled_mask=ismember(result.mode,["RECONTACT","LOAD_RETURN"]);
first=find(result.recontact_stage=="FIRST_CONTACT",1,'first');
if isempty(first),first=find(active & result.task_s>=.5,1,'first');end
stable=find(result.recontact_stable & controlled_mask,1,'first');
recontact=find(result.mode=="RECONTACT");
load_return=find(result.mode=="LOAD_RETURN");
contact_window=false(size(active));
last_controlled=find(controlled_mask,1,'last');
if ~isempty(first) && ~isempty(last_controlled)
    contact_window(first:last_controlled)=true;
end
active_window=contact_window & active;
metrics=struct('classification',result.terminal_state, ...
    'first_contact_time_s',sample(result.t,first), ...
    'first_contact_force_N',sample(result.bed_force_N,first), ...
    'first_contact_approach_velocity_m_s', ...
    -sample(result.minimum_gap_velocity_m_s,first), ...
    'first_stable_time_s',sample(result.t,stable), ...
    'first_stable_force_N',sample(result.bed_force_N,stable), ...
    'peak_bed_force_N',masked_max(result.bed_force_N,contact_window), ...
    'global_peak_bed_force_N',max(result.bed_force_N), ...
    'minimum_penetration_m',masked_min(result.max_penetration_m,active_window), ...
    'maximum_penetration_m',masked_max(result.max_penetration_m,active_window), ...
    'global_maximum_penetration_m',max(result.max_penetration_m), ...
    'minimum_contact_margin_N',masked_min(result.contact_margin_N,contact_window), ...
    'maximum_contact_margin_N',masked_max(result.contact_margin_N,contact_window), ...
    'final_contact_margin_N',result.contact_margin_N(end), ...
    'maximum_stable_dwell_s',max(result.recontact_stable_time_s), ...
    'contact_chatter_count',transition_count(active,contact_window), ...
    'recontact_duration_s',numel(recontact)*dt, ...
    'load_return_duration_s',numel(load_return)*dt, ...
    'load_return_complete',any(result.mode=="BED_SUPPORTED_RETURN"), ...
    'peak_robot_component_N',max(abs(result.robot_force_N),[],'all'), ...
    'peak_robot_force_norm_N',max(vecnorm(result.robot_force_N,2,1)), ...
    'peak_robot_force_slew_N_s',max(vecnorm(result.force_rate_N_s,2,1)), ...
    'soft_limit_samples',sum(result.soft_limit_active), ...
    'controlled_contact_soft_limit_samples',sum( ...
    result.soft_limit_active & controlled_mask), ...
    'rom_violation_samples',sum(result.rom_violation), ...
    'maximum_reference_deviation_deg',rad2deg(max(vecnorm( ...
    result.recontact_reference_offset_rad,2,1))), ...
    'final_progress',result.task_s(end),'duration_s',result.t(end));
end


function value=sample(vector,index)
if isempty(index),value=NaN;else,value=vector(index);end
end


function value=masked_max(vector,mask)
if any(mask),value=max(vector(mask));else,value=NaN;end
end


function value=masked_min(vector,mask)
if any(mask),value=min(vector(mask));else,value=NaN;end
end


function count=transition_count(active,mask)
indices=find(mask);count=0;
if numel(indices)>1
    values=active(indices(1):indices(end));count=sum(values(2:end)~=values(1:end-1));
end
end
