function run_bed_supported_preposition_smoke()
%RUN_BED_SUPPORTED_PREPOSITION_SMOKE Six short nominal-bed mechanical checks.

set(groot,'DefaultFigureVisible','off');runner_dir=fileparts(mfilename('fullpath'));
repo_root=fileparts(fileparts(fileparts(runner_dir)));
output_dir=fullfile(repo_root,'linkage','results','local', ...
    'bed_supported_load_transfer_v1','smoke_preposition');
if ~isfolder(output_dir),mkdir(output_dir);end
diary_path=fullfile(output_dir,'console.log');if isfile(diary_path),delete(diary_path);end
diary(diary_path);cleanup=onCleanup(@()diary('off'));
p=human_two_link_v2_parameters(1.72,75);bounds=[80 120 200];caps=[5 10];
results=cell(3,2);record_cells=cell(6,1);row=0;
for bi=1:3
 for ci=1:2
  config=bed_supported_v1_config(bounds(bi),caps(ci),"nominal");
  config.plan_node_count=41;config.candidate_step_deg=2;config.max_time_s=16;
  calibration=bed_supported_v1_calibrate_hip_height(p,config);
  plan=hybrid_tube_v1_build_plan(p,config);
  result=simulate_bed_supported_load_transfer_v1(config,p,plan,calibration);
  results{bi,ci}=result;row=row+1;record_cells{row}=record(result);
  fprintf(['SMOKE %gN %gdeg terminal=%s modes=%s q_pre=%s ' ...
   'pred=%s actual=%s bed=%.6g residual=%.6g soft=%d boundary=%d\n'], ...
   bounds(bi),caps(ci),result.terminal_state, ...
   strjoin(cellstr(unique(result.mode,'stable')),'>'), ...
   mat2str(result.metrics.preposition_final_q_deg,6), ...
   mat2str(result.metrics.preposition_robot_only_force_N,6), ...
   mat2str(result.metrics.preposition_actual_robot_force_N,6), ...
   result.metrics.preposition_bed_force_N, ...
   result.metrics.preposition_robot_only_residual_Nm, ...
   result.metrics.soft_limit_count,result.metrics.preposition_boundary_seeking);
 end
end
records=vertcat(record_cells{:});
save(fullfile(output_dir,'smoke_results.mat'),'results','records','-v7.3');
writetable(struct2table(records),fullfile(output_dir,'smoke_metrics.csv'));
write_summary(fullfile(output_dir,'summary.txt'),records);
gif_path=fullfile(output_dir,'nominal_200N_10deg_supported_preposition.gif');
bed_supported_v1_create_smoke_gif(results{3,2},gif_path);
if ~isempty(findall(groot,'Type','figure','Visible','on'))
 error('BedSupportedV1:VisibleSmokeFigure','Smoke runner created a visible figure.');
end
end


function r=record(result)
m=result.metrics;c=result.config;
r=struct('force_bound_N',c.force_bound_N,'tube_cap_deg',c.tube_cap_deg, ...
 'terminal_state',m.terminal_state,'state_sequence', ...
 strjoin(cellstr(unique(result.mode,'stable')),'>'), ...
 'entered_liftoff',any(result.mode=="LIFTOFF"), ...
 'entered_suspended',any(result.mode=="SUSPENDED_MOTION"), ...
 'preposition_q1_deg',m.preposition_final_q_deg(1), ...
 'preposition_q2_deg',m.preposition_final_q_deg(2), ...
 'predicted_parallel_N',m.preposition_robot_only_force_N(1), ...
 'predicted_perp_N',m.preposition_robot_only_force_N(2), ...
 'actual_parallel_N',m.preposition_actual_robot_force_N(1), ...
 'actual_perp_N',m.preposition_actual_robot_force_N(2), ...
 'bed_force_N',m.preposition_bed_force_N, ...
 'bounded_residual_Nm',m.preposition_robot_only_residual_Nm, ...
 'soft_limit_count',m.soft_limit_count, ...
 'boundary_seeking',m.preposition_boundary_seeking);
end


function write_summary(path,records)
file=fopen(path,'w');assert(file>=0);cleanup=onCleanup(@()fclose(file));
fprintf(file,'Bed-supported preposition smoke\nMATLAB %s\n',version);
for k=1:numel(records)
 r=records(k);fprintf(file,['%gN %gdeg: terminal=%s sequence=%s ' ...
  'q_pre=[%.6g %.6g] predicted=[%.6g %.6g] actual=[%.6g %.6g] ' ...
  'bed=%.6g residual=%.6g soft=%d boundary=%d\n'],r.force_bound_N, ...
  r.tube_cap_deg,r.terminal_state,r.state_sequence,r.preposition_q1_deg, ...
  r.preposition_q2_deg,r.predicted_parallel_N,r.predicted_perp_N, ...
  r.actual_parallel_N,r.actual_perp_N,r.bed_force_N,r.bounded_residual_Nm, ...
  r.soft_limit_count,r.boundary_seeking);
end
end
