function run_r3b_recontact_margin_controller()
%RUN_R3B_RECONTACT_MARGIN_CONTROLLER Fixed three-case R3B formal experiment.

set(groot,'DefaultFigureVisible','off');
runner_dir=fileparts(mfilename('fullpath'));
repo_root=fileparts(fileparts(fileparts(runner_dir)));
root=fullfile(repo_root,'linkage','results','local', ...
    'r3b_recontact_margin_controller');
run_id=char(datetime('now','TimeZone','UTC','Format','yyyyMMdd_HHmmss'));
output_dir=fullfile(root,run_id);mkdir(output_dir);
diary(fullfile(output_dir,'console.log'));cleanup=onCleanup(@()diary('off'));
fprintf('R3B RECONTACT MARGIN CONTROLLER MATLAB: %s\n',version);
fprintf('OUTPUT DIRECTORY: %s\n',output_dir);

nominal=human_two_link_v2_parameters(1.72,75);
base_config=dynamic_robust_v1_config();
config=r3b_recontact_margin_config(base_config,1.0);
assert_frozen_contract(base_config,config);
adaptive=dynamic_robust_v1_adaptive_config(config);
calibration=bed_supported_v1_calibrate_hip_height(nominal,config);
plan=hybrid_tube_v1_build_plan(nominal,config);
uncertainty=bed_supported_v1_registered_uncertainty_set(nominal);
mild=bed_supported_v1_parameter_override(nominal, ...
    uncertainty.combined_cases(1).override);
names=["nominal","mild_adaptive","mild_oracle"];
plants={nominal,mild,mild};models={nominal,nominal,mild};
use_adaptive=[true,true,false];results=cell(1,3);
initializations=cell(1,3);records=repmat(empty_record(),3,1);
for index=1:3
    case_config=config;case_config.case_name="r3b_"+names(index);
    initializations{index}=dynamic_robust_v1_initial_admissibility( ...
        nominal,plants{index},calibration,case_config,models{index});
    if ~initializations{index}.pass
        error('R3B:InitialAdmissibilityFailed','%s failed.',names(index));
    end
    fprintf('RUN R3B CASE %s\n',names(index));
    if use_adaptive(index)
        results{index}=simulate_dynamic_robust_load_transfer_v1( ...
            case_config,nominal,plants{index},plan,calibration, ...
            initializations{index},models{index},adaptive);
    else
        results{index}=simulate_dynamic_robust_load_transfer_v1( ...
            case_config,nominal,plants{index},plan,calibration, ...
            initializations{index},models{index});
    end
    records(index)=make_record(names(index),results{index});
    case_dir=fullfile(output_dir,char(names(index)));mkdir(case_dir);
    result=results{index};initialization=initializations{index};
    save(fullfile(case_dir,'result.mat'),'result','initialization','-v7.3');
    dynamic_robust_v1_create_artifacts(results{index},case_dir);
    if use_adaptive(index)
        dynamic_robust_v1_adaptive_create_artifacts(results{index},case_dir);
    end
    fprintf(['R3B %s status=%s t=%.3f s=%.6f first=%.6g N ' ...
        'stable=%.6g N peak=%.6g N maxPen=%.6g m chatter=%d ' ...
        'loadReturn=%d accepted=%d\n'],names(index), ...
        records(index).classification,records(index).duration_s, ...
        records(index).final_progress,records(index).first_contact_force_N, ...
        records(index).first_stable_force_N,records(index).peak_bed_force_N, ...
        records(index).maximum_penetration_m, ...
        records(index).contact_chatter_count, ...
        records(index).load_return_complete,records(index).accepted_updates);
end
old_r2b_path=fullfile(repo_root,'linkage','results','local', ...
    'dynamic_robust_load_transfer_v1_adaptive_tracking_r2b', ...
    '20260816_083505','formal_adaptive_results.mat');
old_r2a_path=fullfile(repo_root,'linkage','results','local', ...
    'dynamic_robust_load_transfer_v1_oracle_model_r2a', ...
    '20260815_174540','formal_oracle_results.mat');
old_r2b=load(old_r2b_path,'results');old_r2a=load(old_r2a_path,'results');
r3b_recontact_create_artifacts(results,names,old_r2b.results{2}, ...
    old_r2a.results{2},output_dir);
save(fullfile(output_dir,'formal_r3b_results.mat'),'results', ...
    'initializations','records','names','plants','models','use_adaptive', ...
    'nominal','base_config','config','adaptive','calibration','plan', ...
    'uncertainty','old_r2b_path','old_r2a_path','-v7.3');
writetable(struct2table(records),fullfile(output_dir,'case_metrics.csv'));
write_summary(fullfile(output_dir,'summary.txt'),records,config);
if ~isempty(findall(groot,'Type','figure','Visible','on'))
    error('R3B:VisibleFigure','R3B created a visible figure.');
end
end


function row=make_record(name,result)
m=r3b_recontact_metrics(result);id=result.metrics.identifier;
row=empty_record();fields=fieldnames(m);
for index=1:numel(fields),row.(fields{index})=m.(fields{index});end
row.case_name=name;row.accepted_updates=id.accepted_updates;
row.rejected_updates=id.rejected_updates;row.solver_failures=id.solver_failures;
row.final_parameter_error=id.final_normalized_error;
end


function row=empty_record()
row=struct('case_name',"",'classification',"",'duration_s',NaN, ...
    'final_progress',NaN,'first_contact_time_s',NaN, ...
    'first_contact_force_N',NaN,'first_contact_approach_velocity_m_s',NaN, ...
    'first_stable_time_s',NaN,'first_stable_force_N',NaN, ...
    'peak_bed_force_N',NaN,'global_peak_bed_force_N',NaN, ...
    'minimum_penetration_m',NaN,'maximum_penetration_m',NaN, ...
    'global_maximum_penetration_m',NaN,'minimum_contact_margin_N',NaN, ...
    'maximum_contact_margin_N',NaN,'final_contact_margin_N',NaN, ...
    'maximum_stable_dwell_s',NaN,'contact_chatter_count',0, ...
    'recontact_duration_s',NaN,'load_return_duration_s',NaN, ...
    'load_return_complete',false,'peak_robot_component_N',NaN, ...
    'peak_robot_force_norm_N',NaN,'peak_robot_force_slew_N_s',NaN, ...
    'soft_limit_samples',0,'controlled_contact_soft_limit_samples',0, ...
    'rom_violation_samples',0, ...
    'maximum_reference_deviation_deg',NaN,'accepted_updates',0, ...
    'rejected_updates',0,'solver_failures',0,'final_parameter_error',NaN);
end


function assert_frozen_contract(base,config)
fields={'contact_force_threshold_N','contact_stable_duration_s', ...
    'recontact_timeout_s','force_bound_N','tube_cap_deg','bed_plane_y_m', ...
    'k_bed_N_m','c_bed_Ns_m','max_time_s'};
for index=1:numel(fields)
    assert(isequaln(base.(fields{index}),config.(fields{index})), ...
        'R3B changed frozen field %s.',fields{index});
end
assert(isequaln(base.u_min,config.u_min)&&isequaln(base.u_max,config.u_max));
end


function write_summary(path,records,config)
file=fopen(path,'w');assert(file>=0);cleanup=onCleanup(@()fclose(file));
fprintf(file,'R3B Recontact Margin Controller\nMATLAB %s\n',version);
fprintf(file,['stable threshold %.9g N; engineering reserve %.9g N; ' ...
    'target %.9g N; unchanged timeout %.9g s\n'], ...
    config.contact_force_threshold_N,config.r3b_contact_reserve_N, ...
    config.r3b_contact_target_N,config.recontact_timeout_s);
for index=1:numel(records)
    r=records(index);fprintf(file,[ ...
        '%s: %s t=%.9g s=%.9g first=%.9g stable=%.9g peak=%.9g ' ...
        'penetration=[%.9g,%.9g] chatter=%d recontact=%.9g ' ...
        'loadReturn=%d forcePeak=%.9g slew=%.9g soft=%d ROM=%d ' ...
        'ID=%d/%d/%d error=%.9g\n'],r.case_name,r.classification, ...
        r.duration_s,r.final_progress,r.first_contact_force_N, ...
        r.first_stable_force_N,r.peak_bed_force_N, ...
        r.minimum_penetration_m,r.maximum_penetration_m, ...
        r.contact_chatter_count,r.recontact_duration_s, ...
        r.load_return_complete,r.peak_robot_component_N, ...
        r.peak_robot_force_slew_N_s,r.soft_limit_samples, ...
        r.rom_violation_samples,r.accepted_updates,r.rejected_updates, ...
        r.solver_failures,r.final_parameter_error);
end
end
