function run_ideal_endpoint_force_baseline()
%RUN_IDEAL_ENDPOINT_FORCE_BASELINE Headless deterministic endpoint-force matrix.

set(groot, 'DefaultFigureVisible', 'off');
runner_dir = fileparts(mfilename('fullpath'));
repo_root = fileparts(fileparts(fileparts(runner_dir)));
output_dir = fullfile(repo_root, 'linkage', 'results', 'local', ...
    'ideal_endpoint_force_baseline');
runs_dir = fullfile(output_dir, 'runs');
if ~isfolder(output_dir)
    mkdir(output_dir);
end
if ~isfolder(runs_dir)
    mkdir(runs_dir);
end

diary_path = fullfile(output_dir, 'baseline_console.log');
if isfile(diary_path)
    delete(diary_path);
end
diary(diary_path);
diary_cleanup = onCleanup(@() diary('off'));

trajectories = [ ...
    "knee_dominant", ...
    "coordinated_path", ...
    "conflicting_boundary"];
profiles = ["nominal", "short_light", "tall_heavy"];
actuator_modes = ["endpoint_force", "oracle_joint_torque"];
base_config = ideal_endpoint_force_config();

profile_parameters = cell(1, numel(profiles));
for profile_index = 1:numel(profiles)
    profile_parameters{profile_index} = default_parameters( ...
        profiles(profile_index));
end
validate_references(trajectories, base_config, profile_parameters{1});
write_command_record(fullfile(output_dir, 'commands.txt'));

version_file = fopen(fullfile(output_dir, 'matlab_version.txt'), 'w');
assert(version_file >= 0, 'Could not create MATLAB version record.');
fprintf(version_file, '%s\n', version);
fclose(version_file);

configuration = struct();
configuration.trajectories = trajectories;
configuration.profiles = profiles;
configuration.actuator_modes = actuator_modes;
configuration.base = base_config;
configuration.profile_parameters = profile_parameters;
configuration.force_interpretation = [ ...
    "u=[Ft;Fn] in the rotating shank-contact frame; " ...
    "F_world=[t n]u; tau_contact=Jc'F_world."];
configuration.authority_note = [ ...
    "Endpoint-force cases have no joint torque. Oracle cases use the " ...
    "retained true-model computed-torque PD and therefore have different " ...
    "actuator authority."];
configuration.scope_note = [ ...
    "Ideal bidirectional cuff upper bound only; no robot dynamics, SDK, " ...
    "patient active torque, hidden clipping, or clinical-safety claim."];
configuration.initialization_note = [ ...
    "q and dq start exactly on the reference. The previous cuff command " ...
    "starts at the same hard-bounded steady reference solution, so the " ...
    "first commanded force rate is zero."];
save(fullfile(output_dir, 'configuration_snapshot.mat'), 'configuration');
write_configuration_text(fullfile(output_dir, ...
    'configuration_snapshot.txt'), configuration);

record_count = numel(trajectories) * numel(profiles) * ...
    numel(actuator_modes);
records = repmat(empty_record(), record_count, 1);
record_index = 0;
representative = [];

fprintf('IDEAL ENDPOINT FORCE BASELINE MATLAB: %s\n', version);
fprintf('IDEAL ENDPOINT FORCE OUTPUT: %s\n', output_dir);
fprintf('IDEAL ENDPOINT FORCE RUN COUNT: %d\n', record_count);

for trajectory_index = 1:numel(trajectories)
    for profile_index = 1:numel(profiles)
        p = profile_parameters{profile_index};
        for mode_index = 1:numel(actuator_modes)
            record_index = record_index + 1;
            config = base_config;
            config.trajectory_name = trajectories(trajectory_index);
            actuator_mode = actuator_modes(mode_index);
            run_id = sprintf('%s__%s__%s', ...
                char(config.trajectory_name), char(p.profile_name), ...
                char(actuator_mode));

            result = simulate_ideal_endpoint_force_episode( ...
                config, p, actuator_mode);
            save(fullfile(runs_dir, run_id + ".mat"), ...
                'result', '-v7');

            records(record_index) = make_record( ...
                run_id, config, p, actuator_mode, result.metrics);
            writetable(struct2table(records(record_index)), ...
                fullfile(runs_dir, run_id + "_metrics.csv"));

            if config.trajectory_name == "coordinated_path" && ...
                    p.profile_name == "nominal" && ...
                    actuator_mode == "endpoint_force"
                representative = result;
            end

            fprintf(['  %02d/%02d %-68s completed=%d ' ...
                'rmse=[%.3f, %.3f]deg residual=%.3fNm ' ...
                'sat=%.3f cond95=%.2f limits=[%d,%d]\n'], ...
                record_index, record_count, run_id, ...
                result.metrics.completed, ...
                rad2deg(result.metrics.rmse_rad(1)), ...
                rad2deg(result.metrics.rmse_rad(2)), ...
                result.metrics.torque_residual_rms_Nm, ...
                result.metrics.hard_saturation_fraction, ...
                result.metrics.condition_p95, ...
                result.metrics.joint_limit_violation_count, ...
                result.metrics.velocity_limit_violation_count);
        end
    end
end

aggregate = struct2table(records);
writetable(aggregate, fullfile(output_dir, 'aggregate_metrics.csv'));
save(fullfile(output_dir, 'aggregate_metrics.mat'), ...
    'aggregate', 'configuration');

if isempty(representative)
    error('IdealEndpointForce:MissingRepresentativeRun', ...
        'The nominal coordinated endpoint-force run was not captured.');
end
gif_path = fullfile(output_dir, ...
    'representative_coordinated_path_nominal.gif');
create_representative_gif(representative, gif_path, output_dir);

visible_figures = findall(groot, 'Type', 'figure', 'Visible', 'on');
if ~isempty(visible_figures)
    error('IdealEndpointForce:VisibleFigure', ...
        'The headless runner created a visible figure.');
end
gif_files = dir(fullfile(output_dir, '*.gif'));
if numel(gif_files) ~= 1
    error('IdealEndpointForce:GifCount', ...
        'Expected exactly one representative GIF, found %d.', ...
        numel(gif_files));
end

endpoint_rows = aggregate.actuator_mode == "endpoint_force";
oracle_rows = aggregate.actuator_mode == "oracle_joint_torque";
fprintf(['IDEAL ENDPOINT FORCE SUMMARY: endpoint_completed=%d/%d ' ...
    'oracle_completed=%d/%d signal_nonfinite=%d ' ...
    'joint_limit_samples=%d velocity_limit_samples=%d gif=%s\n'], ...
    sum(aggregate.completed(endpoint_rows)), sum(endpoint_rows), ...
    sum(aggregate.completed(oracle_rows)), sum(oracle_rows), ...
    sum(aggregate.signal_nonfinite_count), ...
    sum(aggregate.joint_limit_violation_count), ...
    sum(aggregate.velocity_limit_violation_count), gif_path);
end


function validate_references(trajectories, config, p)
t = 0:config.dt:config.t_final;
for trajectory = trajectories
    q = zeros(2, numel(t));
    dq = zeros(2, numel(t));
    ddq = zeros(2, numel(t));
    for index = 1:numel(t)
        [q(:, index), dq(:, index), ddq(:, index)] = ...
            rehabilitation_reference_trajectory(t(index), trajectory);
    end
    if any(q < p.q_min | q > p.q_max, 'all')
        error('IdealEndpointForce:ReferenceJointLimit', ...
            'Reference %s exceeds a configured joint range.', trajectory);
    end
    if any(abs(dq) > p.dq_max, 'all')
        error('IdealEndpointForce:ReferenceVelocityLimit', ...
            'Reference %s exceeds a configured velocity range.', trajectory);
    end
    if any(abs(ddq) > p.reference_ddq_max, 'all')
        error('IdealEndpointForce:ReferenceAccelerationLimit', ...
            'Reference %s exceeds a configured acceleration range.', ...
            trajectory);
    end
end
end


function record = empty_record()
record = struct( ...
    'run_id', "", ...
    'trajectory', "", ...
    'profile', "", ...
    'actuator_mode', "", ...
    'length_scale', 0, ...
    'mass_scale', 0, ...
    'completed', false, ...
    'initial_alignment_error_deg', 0, ...
    'rmse_q1_deg', 0, ...
    'rmse_q2_deg', 0, ...
    'max_error_q1_deg', 0, ...
    'max_error_q2_deg', 0, ...
    'non_target_hip_excursion_deg', NaN, ...
    'path_rmse_deg', NaN, ...
    'path_max_abs_deg', NaN, ...
    'max_velocity_q1_deg_s', 0, ...
    'max_velocity_q2_deg_s', 0, ...
    'max_acceleration_q1_deg_s2', 0, ...
    'max_acceleration_q2_deg_s2', 0, ...
    'max_jerk_q1_deg_s3', 0, ...
    'max_jerk_q2_deg_s3', 0, ...
    'max_abs_Ft_N', NaN, ...
    'max_abs_Fn_N', NaN, ...
    'max_force_norm_N', NaN, ...
    'max_force_rate_N_s', NaN, ...
    'rms_force_rate_N_s', NaN, ...
    'hard_saturation_fraction', NaN, ...
    'slew_saturation_fraction', NaN, ...
    'torque_residual_rms_Nm', NaN, ...
    'torque_residual_max_Nm', NaN, ...
    'condition_median', 0, ...
    'condition_p95', 0, ...
    'condition_max', 0, ...
    'condition_nonfinite_count', 0, ...
    'max_joint_torque_norm_Nm', 0, ...
    'joint_limit_violation_count', 0, ...
    'velocity_limit_violation_count', 0, ...
    'signal_nonfinite_count', 0);
end


function record = make_record(run_id, config, p, actuator_mode, metrics)
record = empty_record();
record.run_id = string(run_id);
record.trajectory = string(config.trajectory_name);
record.profile = string(p.profile_name);
record.actuator_mode = string(actuator_mode);
record.length_scale = p.length_scale;
record.mass_scale = p.mass_scale;
record.completed = metrics.completed;
record.initial_alignment_error_deg = ...
    rad2deg(metrics.initial_alignment_error_rad);
record.rmse_q1_deg = rad2deg(metrics.rmse_rad(1));
record.rmse_q2_deg = rad2deg(metrics.rmse_rad(2));
record.max_error_q1_deg = rad2deg(metrics.max_abs_error_rad(1));
record.max_error_q2_deg = rad2deg(metrics.max_abs_error_rad(2));
record.non_target_hip_excursion_deg = ...
    rad2deg(metrics.non_target_hip_excursion_rad);
record.path_rmse_deg = rad2deg(metrics.path_rmse_rad);
record.path_max_abs_deg = rad2deg(metrics.path_max_abs_rad);
record.max_velocity_q1_deg_s = ...
    rad2deg(metrics.max_abs_velocity_rad_s(1));
record.max_velocity_q2_deg_s = ...
    rad2deg(metrics.max_abs_velocity_rad_s(2));
record.max_acceleration_q1_deg_s2 = ...
    rad2deg(metrics.max_abs_acceleration_rad_s2(1));
record.max_acceleration_q2_deg_s2 = ...
    rad2deg(metrics.max_abs_acceleration_rad_s2(2));
record.max_jerk_q1_deg_s3 = ...
    rad2deg(metrics.max_abs_jerk_rad_s3(1));
record.max_jerk_q2_deg_s3 = ...
    rad2deg(metrics.max_abs_jerk_rad_s3(2));
record.max_abs_Ft_N = metrics.max_abs_Ft_N;
record.max_abs_Fn_N = metrics.max_abs_Fn_N;
record.max_force_norm_N = metrics.max_force_norm_N;
record.max_force_rate_N_s = metrics.max_force_rate_N_s;
record.rms_force_rate_N_s = metrics.rms_force_rate_N_s;
record.hard_saturation_fraction = metrics.hard_saturation_fraction;
record.slew_saturation_fraction = metrics.slew_saturation_fraction;
record.torque_residual_rms_Nm = metrics.torque_residual_rms_Nm;
record.torque_residual_max_Nm = metrics.torque_residual_max_Nm;
record.condition_median = metrics.condition_median;
record.condition_p95 = metrics.condition_p95;
record.condition_max = metrics.condition_max;
record.condition_nonfinite_count = metrics.condition_nonfinite_count;
record.max_joint_torque_norm_Nm = metrics.max_joint_torque_norm_Nm;
record.joint_limit_violation_count = ...
    metrics.joint_limit_violation_count;
record.velocity_limit_violation_count = ...
    metrics.velocity_limit_violation_count;
record.signal_nonfinite_count = metrics.signal_nonfinite_count;
end


function create_representative_gif(result, gif_path, output_dir)
figure_handle = figure('Visible', 'off', ...
    'Color', 'w', 'Position', [20, 20, 1400, 820]);
layout = tiledlayout(figure_handle, 5, 2, ...
    'TileSpacing', 'compact', 'Padding', 'compact');

body_axis = nexttile(layout, 1, [5, 1]);
hold(body_axis, 'on');
axis(body_axis, 'equal');
grid(body_axis, 'on');
p = result.parameters;
reach = p.L1 + p.L2;
xlim(body_axis, [-0.25, reach+0.40]);
ylim(body_axis, [-0.35, reach+0.35]);
xlabel(body_axis, 'X (m)');
ylabel(body_axis, 'Y (m)');
title(body_axis, 'Ideal single-point endpoint force');
body_line = plot(body_axis, nan, nan, 'o-', ...
    'LineWidth', 5, 'MarkerSize', 8, ...
    'Color', [0.10, 0.35, 0.75]);
contact_marker = plot(body_axis, nan, nan, 'o', ...
    'MarkerSize', 10, 'MarkerFaceColor', [0.85, 0.25, 0.15], ...
    'MarkerEdgeColor', 'k');
force_arrow = quiver(body_axis, 0, 0, 0, 0, 0, ...
    'LineWidth', 2.5, 'Color', [0.85, 0.15, 0.10], ...
    'MaxHeadSize', 0.8);
text(body_axis, 0.02, 0.98, ...
    'Force arrow scale: 1 N = 0.0012 m', ...
    'Units', 'normalized', 'VerticalAlignment', 'top');

t = result.t;
q_axis = nexttile(layout, 2);
hold(q_axis, 'on');
plot(q_axis, t, rad2deg(result.q_ref(1, :)), '--', ...
    'Color', [0.2, 0.4, 0.9]);
plot(q_axis, t, rad2deg(result.q_ref(2, :)), '--', ...
    'Color', [0.9, 0.4, 0.2]);
q1_actual = plot(q_axis, nan, nan, '-', ...
    'Color', [0.05, 0.2, 0.65], 'LineWidth', 1.5);
q2_actual = plot(q_axis, nan, nan, '-', ...
    'Color', [0.70, 0.15, 0.05], 'LineWidth', 1.5);
grid(q_axis, 'on');
xlim(q_axis, [t(1), t(end)]);
ylabel(q_axis, 'Angle (deg)');
title(q_axis, 'q_1/q_2 reference and actual');
legend(q_axis, {'q_1 ref', 'q_2 ref', 'q_1', 'q_2'}, ...
    'Location', 'eastoutside');

force_axis = nexttile(layout, 4);
hold(force_axis, 'on');
Ft_line = plot(force_axis, nan, nan, 'LineWidth', 1.3);
Fn_line = plot(force_axis, nan, nan, 'LineWidth', 1.3);
force_norm_line = plot(force_axis, nan, nan, 'k-', 'LineWidth', 1.3);
grid(force_axis, 'on');
xlim(force_axis, [t(1), t(end)]);
ylabel(force_axis, 'Force (N)');
title(force_axis, 'Local cuff force');
legend(force_axis, {'F_t', 'F_n', '||F||'}, ...
    'Location', 'eastoutside');

motion_axis = nexttile(layout, 6);
hold(motion_axis, 'on');
acceleration_line = plot(motion_axis, nan, nan, ...
    'Color', [0.1, 0.55, 0.2], 'LineWidth', 1.3);
jerk_line = plot(motion_axis, nan, nan, ...
    'Color', [0.55, 0.15, 0.65], 'LineWidth', 1.3);
grid(motion_axis, 'on');
xlim(motion_axis, [t(1), t(end)]);
ylabel(motion_axis, 'Norm');
title(motion_axis, 'Acceleration (deg/s^2) and jerk (deg/s^3)');
legend(motion_axis, {'||ddq||', '||jerk||'}, ...
    'Location', 'eastoutside');

error_axis = nexttile(layout, 8);
hold(error_axis, 'on');
tracking_line = plot(error_axis, nan, nan, ...
    'Color', [0.10, 0.35, 0.75], 'LineWidth', 1.3);
path_line = plot(error_axis, nan, nan, ...
    'Color', [0.85, 0.25, 0.15], 'LineWidth', 1.3);
grid(error_axis, 'on');
xlim(error_axis, [t(1), t(end)]);
ylabel(error_axis, 'Error (deg)');
title(error_axis, 'Tracking and coordinated-path error');
legend(error_axis, {'||q-q_{ref}||', '|path deviation|'}, ...
    'Location', 'eastoutside');

condition_axis = nexttile(layout, 10);
yyaxis(condition_axis, 'left');
condition_line = plot(condition_axis, nan, nan, ...
    'Color', [0.20, 0.20, 0.20], 'LineWidth', 1.3);
ylabel(condition_axis, 'cond(A)');
yyaxis(condition_axis, 'right');
saturation_line = stairs(condition_axis, nan, nan, ...
    'Color', [0.85, 0.20, 0.15], 'LineWidth', 1.3);
ylim(condition_axis, [-0.05, 1.05]);
ylabel(condition_axis, 'Saturation');
grid(condition_axis, 'on');
xlim(condition_axis, [t(1), t(end)]);
xlabel(condition_axis, 'Time (s)');
title(condition_axis, 'Contact-map conditioning and hard saturation');

axes_with_markers = [q_axis, force_axis, motion_axis, ...
    error_axis, condition_axis];
time_markers = gobjects(size(axes_with_markers));
for marker_index = 1:numel(axes_with_markers)
    marker_axis = axes_with_markers(marker_index);
    hold(marker_axis, 'on');
    time_markers(marker_index) = plot(marker_axis, ...
        [t(1), t(1)], ylim(marker_axis), 'k:', 'LineWidth', 0.8, ...
        'HandleVisibility', 'off');
end

frame_indices = unique(round(linspace(1, numel(t), 65)));
frame_path = fullfile(output_dir, 'representative_frame.png');
force_scale = 0.0012;
delay_time = result.config.t_final / numel(frame_indices);

for frame_number = 1:numel(frame_indices)
    index = frame_indices(frame_number);
    geometry = kinematics(result.state(1:2, index), p);
    contact = shank_contact_kinematics( ...
        result.state(1:2, index), result.state(3:4, index), p);
    points = [geometry.hip, geometry.knee, geometry.ankle];
    set(body_line, 'XData', points(1, :), 'YData', points(2, :));
    set(contact_marker, 'XData', contact.position(1), ...
        'YData', contact.position(2));
    world_force = result.force_world(:, index);
    set(force_arrow, 'XData', contact.position(1), ...
        'YData', contact.position(2), ...
        'UData', force_scale*world_force(1), ...
        'VData', force_scale*world_force(2));
    title(body_axis, sprintf( ...
        'Coordinated path, nominal: t = %.2f s, ||F|| = %.1f N', ...
        t(index), norm(result.force_local(:, index))));

    active = 1:index;
    set(q1_actual, 'XData', t(active), ...
        'YData', rad2deg(result.state(1, active)));
    set(q2_actual, 'XData', t(active), ...
        'YData', rad2deg(result.state(2, active)));
    set(Ft_line, 'XData', t(active), ...
        'YData', result.force_local(1, active));
    set(Fn_line, 'XData', t(active), ...
        'YData', result.force_local(2, active));
    set(force_norm_line, 'XData', t(active), ...
        'YData', vecnorm(result.force_local(:, active), 2, 1));
    set(acceleration_line, 'XData', t(active), ...
        'YData', rad2deg(vecnorm( ...
        result.acceleration(:, active), 2, 1)));
    set(jerk_line, 'XData', t(active), ...
        'YData', rad2deg(vecnorm(result.jerk(:, active), 2, 1)));
    set(tracking_line, 'XData', t(active), ...
        'YData', rad2deg(result.tracking_error_norm(active)));
    set(path_line, 'XData', t(active), ...
        'YData', rad2deg(abs(result.path_error(active))));
    set(condition_line, 'XData', t(active), ...
        'YData', result.condition_number(active));
    set(saturation_line, 'XData', t(active), ...
        'YData', double(result.hard_saturation(active)));
    for marker_index = 1:numel(time_markers)
        set(time_markers(marker_index), ...
            'XData', [t(index), t(index)]);
    end

    exportgraphics(figure_handle, frame_path, 'Resolution', 90);
    rgb_frame = imread(frame_path);
    [indexed_frame, color_map] = rgb2ind(rgb_frame, 256);
    if frame_number == 1
        imwrite(indexed_frame, color_map, gif_path, 'gif', ...
            'LoopCount', Inf, 'DelayTime', delay_time);
    else
        imwrite(indexed_frame, color_map, gif_path, 'gif', ...
            'WriteMode', 'append', 'DelayTime', delay_time);
    end
end

close(figure_handle);
if isfile(frame_path)
    delete(frame_path);
end
end


function write_command_record(path)
output_file = fopen(path, 'w');
assert(output_file >= 0, 'Could not create command record.');
cleanup = onCleanup(@() fclose(output_file));
fprintf(output_file, '%s\n', ...
    ['/Users/hankli/Desktop/MATLAB_R2025b.app/bin/matlab ' ...
    '-batch "addpath(genpath(''linkage/matlab'')); ' ...
    'run_ideal_endpoint_force_tests"']);
fprintf(output_file, '%s\n', ...
    ['/Users/hankli/Desktop/MATLAB_R2025b.app/bin/matlab ' ...
    '-batch "addpath(genpath(''linkage/matlab'')); ' ...
    'run_ideal_endpoint_force_baseline"']);
end


function write_configuration_text(path, configuration)
output_file = fopen(path, 'w');
assert(output_file >= 0, 'Could not create configuration text snapshot.');
cleanup = onCleanup(@() fclose(output_file));
config = configuration.base;

fprintf(output_file, 'MATLAB: %s\n', version);
fprintf(output_file, 'dt: %.17g s\n', config.dt);
fprintf(output_file, 't_final: %.17g s\n', config.t_final);
fprintf(output_file, 'accel_Kp: %s\n', mat2str(config.accel_Kp));
fprintf(output_file, 'accel_Kd: %s\n', mat2str(config.accel_Kd));
fprintf(output_file, 'W_tau: %s\n', mat2str(config.W_tau));
fprintf(output_file, 'lambda_u: %.17g\n', config.lambda_u);
fprintf(output_file, 'lambda_du: %.17g\n', config.lambda_du);
fprintf(output_file, 'u_min [Ft Fn] N: %s\n', mat2str(config.u_min'));
fprintf(output_file, 'u_max [Ft Fn] N: %s\n', mat2str(config.u_max'));
fprintf(output_file, 'du_max [Ft Fn] N/s: %s\n', ...
    mat2str(config.du_max'));
fprintf(output_file, 'oracle_Kp: %s\n', mat2str(config.oracle_Kp));
fprintf(output_file, 'oracle_Kd: %s\n', mat2str(config.oracle_Kd));
fprintf(output_file, 'trajectories: %s\n', ...
    strjoin(configuration.trajectories, ', '));
fprintf(output_file, 'profiles: %s\n', ...
    strjoin(configuration.profiles, ', '));
fprintf(output_file, '%s\n', configuration.force_interpretation);
fprintf(output_file, '%s\n', configuration.authority_note);
fprintf(output_file, '%s\n', configuration.scope_note);
fprintf(output_file, '%s\n', configuration.initialization_note);
for index = 1:numel(configuration.profiles)
    p = configuration.profile_parameters{index};
    fprintf(output_file, ...
        ['profile=%s length_scale=%.4f mass_scale=%.4f ' ...
        'L1=%.6f L2=%.6f m1=%.6f m2=%.6f sc=%.6f\n'], ...
        p.profile_name, p.length_scale, p.mass_scale, ...
        p.L1, p.L2, p.m1, p.m2, p.sc);
end
end
