function run_r3_identifiability_failure_decomposition()
%RUN_R3_IDENTIFIABILITY_FAILURE_DECOMPOSITION Offline formal-log audit only.

set(groot,'DefaultFigureVisible','off');
runner_dir=fileparts(mfilename('fullpath'));
repo_root=fileparts(fileparts(fileparts(runner_dir)));
paths=r3a_source_paths(repo_root);before=r3a_source_manifest(paths);
run_id=char(datetime('now','TimeZone','UTC','Format','yyyyMMdd_HHmmss'));
output_dir=fullfile(paths.output_root,run_id);mkdir(output_dir);
diary(fullfile(output_dir,'console.log'));cleanup=onCleanup(@()diary('off'));
fprintf('R3A IDENTIFIABILITY / FAILURE DECOMPOSITION MATLAB: %s\n',version);
fprintf('OFFLINE OUTPUT DIRECTORY: %s\n',output_dir);
fprintf('NO CLOSED-LOOP SIMULATION IS RUN BY THIS ANALYSIS.\n');
r1=load(paths.r1);r2a=load(paths.r2a);r2b=load(paths.r2b);

identifier=r3a_identifier_analysis(r2b);
moderate_comparison=[ ...
    r3a_moderate_event_rows(r1.results{3},"nominal_model"); ...
    r3a_moderate_event_rows(r2b.results{3},"adaptive"); ...
    r3a_moderate_event_rows(r2a.results{3},"oracle")];
moderate_replay=r3a_moderate_state_conditioned_replay(r2b.results{3});
[mild_nominal,mild_nominal_summary]=r3a_recontact_diagnostics( ...
    r1.results{2},"nominal_model");
[mild_adaptive,mild_adaptive_summary]=r3a_recontact_diagnostics( ...
    r2b.results{2},"adaptive");
[mild_oracle,mild_oracle_summary]=r3a_recontact_diagnostics( ...
    r2a.results{2},"oracle");
mild_recontact=[mild_nominal;mild_adaptive;mild_oracle];
mild_summaries=[mild_nominal_summary;mild_adaptive_summary;mild_oracle_summary];
phase_segments=cell(4,1);
for index=1:4
    phase_segments{index}=r3a_phase_segments( ...
        r2b.results{index}.mode,r2b.results{index}.t);
end

writetable(identifier.window_diagnostics,fullfile(output_dir, ...
    'identifier_window_diagnostics.csv'));
writetable(identifier.singular_value_summary,fullfile(output_dir, ...
    'singular_value_summary.csv'));
writetable(identifier.parameter_correlation_summary,fullfile(output_dir, ...
    'parameter_correlation_summary.csv'));
writetable(identifier.phase_information_summary,fullfile(output_dir, ...
    'phase_information_summary.csv'));
writetable(identifier.identifiable_subspace_summary,fullfile(output_dir, ...
    'identifiable_subspace_summary.csv'));
writetable(identifier.subspace_overlap_summary,fullfile(output_dir, ...
    'subspace_overlap_summary.csv'));
writetable(moderate_comparison,fullfile(output_dir, ...
    'moderate_failure_comparison.csv'));
writetable(moderate_replay,fullfile(output_dir, ...
    'moderate_state_conditioned_replay.csv'));
writetable(mild_recontact,fullfile(output_dir, ...
    'mild_recontact_diagnostics.csv'));
writetable(struct2table(mild_summaries),fullfile(output_dir, ...
    'mild_recontact_summary.csv'));
writetable(before,fullfile(output_dir,'source_manifest.csv'));
r3a_create_figures(identifier,r1,r2a,r2b,moderate_replay, ...
    mild_recontact,output_dir);
write_summary(fullfile(output_dir,'summary.txt'),identifier, ...
    moderate_comparison,mild_summaries,paths);

after=r3a_source_manifest(paths);
if ~isequaln(before(:,{'path','bytes','modified_datenum'}), ...
        after(:,{'path','bytes','modified_datenum'}))
    error('R3A:SourceMutation','A frozen formal source changed during R3A.');
end
save(fullfile(output_dir,'r3a_analysis_workspace.mat'),'identifier', ...
    'moderate_comparison','moderate_replay','mild_recontact', ...
    'mild_summaries','phase_segments','paths','before','after','-v7.3');
if ~isempty(findall(groot,'Type','figure','Visible','on'))
    error('R3A:VisibleFigure','R3A created a visible figure.');
end
fprintf('R3A OFFLINE ANALYSIS COMPLETE: %s\n',output_dir);
end


function write_summary(path,identifier,moderate,mild,paths)
file=fopen(path,'w');assert(file>=0);cleanup=onCleanup(@()fclose(file));
fprintf(file,'R3A Identifiability and Failure-Mode Decomposition\n');
fprintf(file,'MATLAB %s\nOFFLINE ONLY; no closed-loop trajectory generated.\n',version);
fprintf(file,'R1 source: %s\nR2A source: %s\nR2B source: %s\n\n', ...
    paths.r1,paths.r2a,paths.r2b);
for index=1:4
    item=identifier.case_info(index);
    fprintf(file,['%s: rank evolution %s; final rank %d; stacked rank %d; ' ...
        'accepted %d / attempts %d\n'],item.name,mat2str(item.ranks'), ...
        r3a_effective_rank(item.final_J),r3a_effective_rank(item.stacked_J), ...
        sum(item.accepted),numel(item.accepted));
end
adverse=identifier.case_info(4);
fprintf(file,'Adverse final sigma/sigma1: %s\n',mat2str( ...
    (adverse.final_singular_values/adverse.final_singular_values(1))',6));
fprintf(file,'Adverse stacked condition: %.9g (R2B limit %.9g)\n', ...
    cond(adverse.stacked_J),1/sqrt(eps));
fprintf(file,'\nModerate checkpoints:\n');
for index=1:height(moderate)
    row=moderate(index,:);fprintf(file, ...
        '%s %s: t=%.6g tracking=%.6g progress=%.9g q2clear=%.9g error=%.9g\n', ...
        row.source,row.event,row.time_s,row.tracking_time_s,row.progress, ...
        row.q2_soft_clearance_deg,row.parameter_error);
end
fprintf(file,'\nMild recontact:\n');
for index=1:numel(mild)
    item=mild(index);fprintf(file,[ ...
        '%s reached=%d start=%.6g end=%.6g span=%.6g samples=%d ' ...
        'activeTransitions=%d thresholdTransitions=%d maxThreshold=%.6g ' ...
        'finalGap=%.9g finalGapVelocity=%.9g finalBed=%.9g finalError=%.9g\n'], ...
        item.source,item.reached,item.start_time_s,item.end_time_s, ...
        item.logged_span_s,item.sample_count,item.active_transitions, ...
        item.threshold_transitions,item.maximum_continuous_threshold_s, ...
        item.final_min_gap_m,item.final_gap_velocity_m_s, ...
        item.final_bed_force_N,item.final_parameter_error);
end
end
