function run_dynamic_robust_load_transfer_v1()
%RUN_DYNAMIC_ROBUST_LOAD_TRANSFER_V1 Formal fixed capability experiment.
%
% Stage 2 is executed only when the nominal Stage 1 reaches TASK_COMPLETE.

set(groot,'DefaultFigureVisible','off');
runner_dir=fileparts(mfilename('fullpath'));
repo_root=fileparts(fileparts(fileparts(runner_dir)));
root=fullfile(repo_root,'linkage','results','local', ...
    'dynamic_robust_load_transfer_v1');
run_id=char(datetime('now','TimeZone','UTC','Format','yyyyMMdd_HHmmss'));
output_dir=fullfile(root,run_id);mkdir(output_dir);
diary(fullfile(output_dir,'console.log'));cleanup=onCleanup(@()diary('off'));
fprintf('DYNAMIC ROBUST LOAD TRANSFER V1 MATLAB: %s\n',version);
fprintf('OUTPUT DIRECTORY: %s\n',output_dir);
fprintf(['FORMAL COMMAND: matlab -batch "addpath(genpath(''' ...
    'linkage/matlab'')); run_dynamic_robust_load_transfer_v1"\n']);

nominal=human_two_link_v2_parameters(1.72,75);
config=dynamic_robust_v1_config();
calibration=bed_supported_v1_calibrate_hip_height(nominal,config);
plan=hybrid_tube_v1_build_plan(nominal,config);
uncertainty=bed_supported_v1_registered_uncertainty_set(nominal);
case_names=["nominal","mild","moderate","adverse"];
results=cell(1,4);records=repmat(empty_record(),0,1);
admissibility_records=repmat(empty_admissibility_record(),0,1);

[results{1},initialization]=run_case( ...
    case_names(1),nominal,config,plan,calibration,output_dir);
records(end+1)=make_record(case_names(1),results{1}); %#ok<AGROW>
admissibility_records(end+1)=make_admissibility_record( ...
    case_names(1),initialization); %#ok<AGROW>
if results{1}.terminal_state=="TASK_COMPLETE"
    for k=1:3
        item=uncertainty.combined_cases(k);
        plant=bed_supported_v1_parameter_override(nominal,item.override);
        [results{k+1},initialization]=run_case( ...
            case_names(k+1),plant,config,plan,calibration,output_dir);
        records(end+1)=make_record(case_names(k+1),results{k+1}); %#ok<AGROW>
        admissibility_records(end+1)=make_admissibility_record( ...
            case_names(k+1),initialization); %#ok<AGROW>
    end
else
    fprintf('STAGE 2 SKIPPED: nominal classification=%s\n', ...
        results{1}.terminal_state);
end
save(fullfile(output_dir,'formal_results.mat'),'results','records', ...
    'admissibility_records','nominal','config','calibration', ...
    'uncertainty','-v7.3');
writetable(struct2table(records),fullfile(output_dir,'case_metrics.csv'));
writetable(struct2table(admissibility_records), ...
    fullfile(output_dir,'initial_admissibility.csv'));
write_summary(fullfile(output_dir,'summary.txt'),records);
if numel(records)>1,create_cross_case_figure(records,output_dir);end
if ~isempty(findall(groot,'Type','figure','Visible','on'))
    error('DynamicRobustV1:VisibleFigure','Formal runner created a visible figure.');
end
end


function [result,initialization]=run_case( ...
        name,plant,config,plan,calibration,output_dir)
nominal=human_two_link_v2_parameters(1.72,75);
case_config=config;case_config.case_name="dynamic_robust_"+name;
fprintf('RUN CASE %s\n',name);
initialization=dynamic_robust_v1_initial_admissibility( ...
    nominal,plant,calibration,case_config);
case_dir=fullfile(output_dir,char(name));mkdir(case_dir);
write_initial_admissibility( ...
    fullfile(case_dir,'initial_admissibility.txt'),name,initialization);
print_initial_admissibility(name,initialization);
if ~initialization.pass
    error('DynamicRobustV1:InitialAdmissibilityFailed', ...
        'Case %s failed initial admissibility; rollout was not started.',name);
end
result=simulate_dynamic_robust_load_transfer_v1( ...
    case_config,nominal,plant,plan,calibration,initialization);
save(fullfile(case_dir,'result.mat'),'result','-v7.3');
dynamic_robust_v1_create_artifacts(result,case_dir);
fprintf('CASE %s classification=%s t=%.3f s=%.6f peak=%.3fN\n', ...
    name,result.terminal_state,result.t(end),result.task_s(end), ...
    result.metrics.peak_force_norm_N);
end


function row=empty_admissibility_record()
row=struct('case_name',"",'pass',false,'q1_deg',NaN,'q2_deg',NaN, ...
    'dq1_deg_s',NaN,'dq2_deg_s',NaN,'q1_soft_clearance_deg',NaN, ...
    'q2_soft_clearance_deg',NaN,'true_soft1_torque_Nm',NaN, ...
    'true_soft2_torque_Nm',NaN,'soft_torque_tolerance_Nm',NaN, ...
    'q1_rom_lower_margin_deg',NaN,'q2_rom_lower_margin_deg',NaN, ...
    'q1_rom_upper_margin_deg',NaN,'q2_rom_upper_margin_deg',NaN, ...
    'bed_force_N',NaN,'bed_force_threshold_N',NaN, ...
    'true_equilibrium_parallel_N',NaN,'true_equilibrium_perp_N',NaN, ...
    'model_equilibrium_parallel_N',NaN,'model_equilibrium_perp_N',NaN, ...
    'ungoverned_nominal_first_candidate_parallel_N',NaN, ...
    'ungoverned_nominal_first_candidate_perp_N',NaN, ...
    'force_bound_N',NaN,'true_equilibrium_force_margin_N',NaN, ...
    'ungoverned_nominal_first_candidate_force_margin_N',NaN, ...
    'true_equilibrium_alpha1_deg_s2',NaN, ...
    'true_equilibrium_alpha2_deg_s2',NaN, ...
    'true_ungoverned_candidate_alpha1_deg_s2',NaN, ...
    'true_ungoverned_candidate_alpha2_deg_s2',NaN, ...
    'model_ungoverned_candidate_alpha1_deg_s2',NaN, ...
    'model_ungoverned_candidate_alpha2_deg_s2',NaN, ...
    'legacy_true_alpha1_deg_s2',NaN,'legacy_true_alpha2_deg_s2',NaN);
end


function row=make_admissibility_record(name,a)
row=empty_admissibility_record();row.case_name=name;row.pass=a.pass;
row.q1_deg=a.q_deg(1);row.q2_deg=a.q_deg(2);
row.dq1_deg_s=a.dq_deg_s(1);row.dq2_deg_s=a.dq_deg_s(2);
row.q1_soft_clearance_deg=a.true_soft_clearance_deg(1);
row.q2_soft_clearance_deg=a.true_soft_clearance_deg(2);
row.true_soft1_torque_Nm=a.true_soft_torque_Nm(1);
row.true_soft2_torque_Nm=a.true_soft_torque_Nm(2);
row.soft_torque_tolerance_Nm=a.soft_torque_tolerance_Nm;
row.q1_rom_lower_margin_deg=a.true_rom_lower_margin_deg(1);
row.q2_rom_lower_margin_deg=a.true_rom_lower_margin_deg(2);
row.q1_rom_upper_margin_deg=a.true_rom_upper_margin_deg(1);
row.q2_rom_upper_margin_deg=a.true_rom_upper_margin_deg(2);
row.bed_force_N=a.bed_force_N;
row.bed_force_threshold_N=a.bed_force_threshold_N;
row.true_equilibrium_parallel_N=a.true_equilibrium_force_N(1);
row.true_equilibrium_perp_N=a.true_equilibrium_force_N(2);
row.model_equilibrium_parallel_N=a.model_equilibrium_force_N(1);
row.model_equilibrium_perp_N=a.model_equilibrium_force_N(2);
row.ungoverned_nominal_first_candidate_parallel_N= ...
    a.first_command_force_N(1);
row.ungoverned_nominal_first_candidate_perp_N=a.first_command_force_N(2);
row.force_bound_N=a.force_bound_N;
row.true_equilibrium_force_margin_N=a.true_equilibrium_force_margin_N;
row.ungoverned_nominal_first_candidate_force_margin_N= ...
    a.first_command_force_margin_N;
row.true_equilibrium_alpha1_deg_s2=a.true_equilibrium_alpha_deg_s2(1);
row.true_equilibrium_alpha2_deg_s2=a.true_equilibrium_alpha_deg_s2(2);
row.true_ungoverned_candidate_alpha1_deg_s2= ...
    a.true_first_command_alpha_deg_s2(1);
row.true_ungoverned_candidate_alpha2_deg_s2= ...
    a.true_first_command_alpha_deg_s2(2);
row.model_ungoverned_candidate_alpha1_deg_s2= ...
    a.model_first_command_alpha_deg_s2(1);
row.model_ungoverned_candidate_alpha2_deg_s2= ...
    a.model_first_command_alpha_deg_s2(2);
row.legacy_true_alpha1_deg_s2=a.legacy_true_first_alpha_deg_s2(1);
row.legacy_true_alpha2_deg_s2=a.legacy_true_first_alpha_deg_s2(2);
end


function print_initial_admissibility(name,a)
fprintf(['INITIAL ADMISSIBILITY %s pass=%d q=[%.9g %.9g]deg ' ...
    'soft_clearance=[%.9g %.9g]deg soft_tau=[%.9g %.9g]Nm ' ...
    'bed=%.9g/%.9gN true_eq=[%.9g %.9g]N model_eq=[%.9g %.9g]N ' ...
    'ungoverned_candidate=[%.9g %.9g]N ' ...
    'true_candidate_alpha=[%.9g %.9g]deg/s^2 ' ...
    'model_alpha=[%.9g %.9g]deg/s^2\n'],name,a.pass,a.q_deg, ...
    a.true_soft_clearance_deg,a.true_soft_torque_Nm,a.bed_force_N, ...
    a.bed_force_threshold_N,a.true_equilibrium_force_N, ...
    a.model_equilibrium_force_N,a.first_command_force_N, ...
    a.true_first_command_alpha_deg_s2,a.model_first_command_alpha_deg_s2);
end


function write_initial_admissibility(path,name,a)
file=fopen(path,'w');assert(file>=0);cleanup=onCleanup(@()fclose(file));
fprintf(file,'case=%s\npass=%d\n',name,a.pass);
fprintf(file,'q_deg=[%.12g %.12g]\ndq_deg_s=[%.12g %.12g]\n', ...
    a.q_deg,a.dq_deg_s);
fprintf(file,['true_soft_lower_start_deg=[%.12g %.12g]\n' ...
    'true_soft_upper_start_deg=[%.12g %.12g]\n' ...
    'true_soft_clearance_deg=[%.12g %.12g]\n' ...
    'model_soft_clearance_deg=[%.12g %.12g]\n'], ...
    a.true_soft_lower_start_deg,a.true_soft_upper_start_deg, ...
    a.true_soft_clearance_deg,a.model_soft_clearance_deg);
fprintf(file,['true_soft_torque_Nm=[%.12g %.12g]\n' ...
    'model_soft_torque_Nm=[%.12g %.12g]\n' ...
    'soft_torque_tolerance_Nm=%.12g\n'],a.true_soft_torque_Nm, ...
    a.model_soft_torque_Nm,a.soft_torque_tolerance_Nm);
fprintf(file,['rom_lower_margin_deg=[%.12g %.12g]\n' ...
    'rom_upper_margin_deg=[%.12g %.12g]\n'], ...
    a.true_rom_lower_margin_deg,a.true_rom_upper_margin_deg);
fprintf(file,'bed_force_N=%.12g\nbed_force_threshold_N=%.12g\n', ...
    a.bed_force_N,a.bed_force_threshold_N);
fprintf(file,['true_equilibrium_force_N=[%.12g %.12g]\n' ...
    'model_equilibrium_force_N=[%.12g %.12g]\n' ...
    'ungoverned_nominal_first_candidate_force_N=[%.12g %.12g]\n' ...
    'force_bound_N=%.12g\n'], ...
    a.true_equilibrium_force_N,a.model_equilibrium_force_N, ...
    a.first_command_force_N,a.force_bound_N);
fprintf(file,['true_equilibrium_alpha_deg_s2=[%.12g %.12g]\n' ...
    'true_ungoverned_candidate_alpha_deg_s2=[%.12g %.12g]\n' ...
    'model_ungoverned_candidate_alpha_deg_s2=[%.12g %.12g]\n' ...
    'legacy_true_first_alpha_deg_s2=[%.12g %.12g]\n'], ...
    a.true_equilibrium_alpha_deg_s2,a.true_first_command_alpha_deg_s2, ...
    a.model_first_command_alpha_deg_s2,a.legacy_true_first_alpha_deg_s2);
end


function row=empty_record()
row=struct('case_name',"",'classification',"",'duration_s',NaN, ...
    'completion_time_s',NaN,'final_s',NaN,'state_sequence',"", ...
    'tracking_entered',false,'takeover_duration_s',NaN, ...
    'failure_phase',"",'takeover_min_q1_deg',NaN, ...
    'takeover_min_soft_margin_deg',NaN,'takeover_hold_steps',NaN, ...
    'takeover_scaled_steps',NaN,'takeover_full_steps',NaN, ...
    'takeover_minimum_lambda',NaN,'minimum_bed_support_N',NaN, ...
    'rmse_q1_deg',NaN,'rmse_q2_deg',NaN,'max_q1_error_deg',NaN, ...
    'max_q2_error_deg',NaN,'max_tube_deviation_deg',NaN, ...
    'peak_parallel_N',NaN,'peak_perp_N',NaN,'peak_force_norm_N',NaN, ...
    'rms_force_N',NaN,'peak_force_rate_N_s',NaN, ...
    'force_saturation_fraction',NaN,'min_robust_static_margin_N',NaN, ...
    'min_dynamic_margin_N',NaN,'min_realized_dynamic_margin_N',NaN, ...
    'peak_realized_dynamic_force_N',NaN,'time_below_20N_s',NaN, ...
    'time_below_10N_s',NaN,'time_below_5N_s',NaN, ...
    'dynamic_residual_rms_Nm',NaN,'dynamic_residual_max_Nm',NaN, ...
    'realized_dynamic_residual_rms_Nm',NaN, ...
    'realized_dynamic_residual_max_Nm',NaN, ...
    'sigma_min_min',NaN,'condition_number_max',NaN, ...
    'initial_bed_force_N',NaN,'transfer_ready_bed_force_N',NaN, ...
    'liftoff_bed_force_N',NaN,'peak_bed_force_N',NaN, ...
    'recontact_bed_force_N',NaN,'load_return_duration_s',NaN, ...
    'contact_chatter_count',NaN,'rom_violation_samples',NaN, ...
    'soft_limit_samples',NaN,'max_soft_limit_torque_Nm',NaN, ...
    'min_soft_zone_clearance_deg',NaN,'transfer_ready_s',NaN, ...
    'transfer_ready_q1_deg',NaN,'transfer_ready_q2_deg',NaN, ...
    'liftoff_s',NaN,'liftoff_q1_deg',NaN,'liftoff_q2_deg',NaN, ...
    'recontact_s',NaN,'recontact_q1_deg',NaN,'recontact_q2_deg',NaN, ...
    'load_return_s',NaN,'load_return_q1_deg',NaN, ...
    'load_return_q2_deg',NaN);
end


function row=make_record(name,result)
m=result.metrics;row=empty_record();row.case_name=name;
row.classification=m.classification;row.duration_s=m.duration_s;
row.completion_time_s=m.completion_time_s;row.final_s=m.final_s;
row.state_sequence=strjoin(m.state_sequence," -> ");
row.tracking_entered=m.takeover_tracking_entered;
row.takeover_duration_s=m.takeover_duration_s;
row.failure_phase=m.failure_phase;
row.takeover_min_q1_deg=m.takeover_min_q1_deg;
row.takeover_min_soft_margin_deg=m.takeover_min_soft_zone_clearance_deg;
row.takeover_hold_steps=m.takeover_hold_steps;
row.takeover_scaled_steps=m.takeover_scaled_steps;
row.takeover_full_steps=m.takeover_full_steps;
row.takeover_minimum_lambda=m.takeover_minimum_lambda;
row.minimum_bed_support_N=min(result.bed_force_N);
row.rmse_q1_deg=m.rmse_q_deg(1);row.rmse_q2_deg=m.rmse_q_deg(2);
row.max_q1_error_deg=m.max_abs_q_error_deg(1);
row.max_q2_error_deg=m.max_abs_q_error_deg(2);
row.max_tube_deviation_deg=max(m.max_tube_deviation_deg);
row.peak_parallel_N=m.peak_abs_parallel_N;row.peak_perp_N=m.peak_abs_perp_N;
row.peak_force_norm_N=m.peak_force_norm_N;row.peak_bed_force_N=m.peak_bed_force_N;
row.rms_force_N=m.rms_force_N;row.peak_force_rate_N_s=m.peak_force_rate_N_s;
row.min_robust_static_margin_N=m.min_robust_static_margin_N;
row.min_dynamic_margin_N=m.min_predicted_dynamic_margin_N;
row.min_realized_dynamic_margin_N=m.min_realized_dynamic_margin_N;
row.peak_realized_dynamic_force_N=m.peak_realized_dynamic_force_N;
row.force_saturation_fraction=m.force_saturation_fraction;
row.time_below_20N_s=m.time_robust_below_20N_s;
row.time_below_10N_s=m.time_robust_below_10N_s;
row.time_below_5N_s=m.time_robust_below_5N_s;
row.dynamic_residual_rms_Nm=m.dynamic_residual_rms_Nm;
row.realized_dynamic_residual_rms_Nm=m.realized_dynamic_residual_rms_Nm;
row.realized_dynamic_residual_max_Nm=m.realized_dynamic_residual_max_Nm;
row.sigma_min_min=m.sigma_min_min;row.condition_number_max=m.condition_number_max;
row.initial_bed_force_N=m.initial_bed_force_N;
row.transfer_ready_bed_force_N=m.events.transfer_ready.bed_force_N;
row.liftoff_bed_force_N=m.events.liftoff.bed_force_N;
row.recontact_bed_force_N=m.events.recontact.bed_force_N;
row.load_return_duration_s=m.events.load_return_duration_s;
row.soft_limit_samples=m.soft_limit_active_samples;
row.max_soft_limit_torque_Nm=m.max_soft_limit_torque_Nm;
row.min_soft_zone_clearance_deg=m.min_soft_zone_clearance_deg;
row.rom_violation_samples=m.rom_violation_samples;
row.contact_chatter_count=m.contact_chatter_count;
row.dynamic_residual_max_Nm=m.dynamic_residual_max_Nm;
row.transfer_ready_s=m.events.transfer_ready.s;
row.transfer_ready_q1_deg=m.events.transfer_ready.q_deg(1);
row.transfer_ready_q2_deg=m.events.transfer_ready.q_deg(2);
row.liftoff_s=m.events.liftoff.s;row.liftoff_q1_deg=m.events.liftoff.q_deg(1);
row.liftoff_q2_deg=m.events.liftoff.q_deg(2);
row.recontact_s=m.events.recontact.s;
row.recontact_q1_deg=m.events.recontact.q_deg(1);
row.recontact_q2_deg=m.events.recontact.q_deg(2);
row.load_return_s=m.events.load_return_complete.s;
row.load_return_q1_deg=m.events.load_return_complete.q_deg(1);
row.load_return_q2_deg=m.events.load_return_complete.q_deg(2);
end


function write_summary(path,records)
file=fopen(path,'w');assert(file>=0);cleanup=onCleanup(@()fclose(file));
fprintf(file,'Dynamic robust load transfer V1\nMATLAB %s\n',version);
for k=1:numel(records)
    r=records(k);fprintf(file,['%s: %s, phase %s, tracking %d, ' ...
        'takeover %.9g s, duration %.9g s, final s %.9g, ' ...
        'peak robot %.9g N, peak bed %.9g N, min robust %.9g N, ' ...
        'min dynamic %.9g N\n'],r.case_name,r.classification, ...
        r.failure_phase,r.tracking_entered,r.takeover_duration_s, ...
        r.duration_s,r.final_s,r.peak_force_norm_N,r.peak_bed_force_N, ...
        r.min_robust_static_margin_N,r.min_dynamic_margin_N);
end
end


function create_cross_case_figure(records,output_dir)
T=struct2table(records);fig=figure('Visible','off','Color','w');
bar(categorical(T.case_name),[T.peak_force_norm_N,T.peak_bed_force_N, ...
    T.min_robust_static_margin_N,T.min_dynamic_margin_N]);grid on;
ylabel('N');legend('peak robot norm','peak bed','min robust','min dynamic');
exportgraphics(fig,fullfile(output_dir,'cross_case_summary.png'),'Resolution',180);close(fig);
end
