function run_r3c_constraint_aware_reference_layer_oracle_gate()
%RUN_R3C_CONSTRAINT_AWARE_REFERENCE_LAYER_ORACLE_GATE Formal R3C Stage 1.

set(groot,'DefaultFigureVisible','off');
runner_dir=fileparts(mfilename('fullpath'));
repo_root=fileparts(fileparts(fileparts(runner_dir)));
root=fullfile(repo_root,'linkage','results','local', ...
    'r3c_constraint_aware_reference_layer');
run_id=char(datetime('now','TimeZone','UTC','Format','yyyyMMdd_HHmmss'));
output_dir=fullfile(root,run_id,'stage1_oracle');mkdir(output_dir);
diary(fullfile(output_dir,'console.log'));cleanup=onCleanup(@()diary('off'));
fprintf(['R3C FORMAL STAGE 1 ORACLE SAFETY CAPABILITY MATLAB: %s\n' ...
    'OUTPUT DIRECTORY: %s\n'],version,output_dir);
nominal=human_two_link_v2_parameters(1.72,75);
base=dynamic_robust_v1_config();config=r3c_constraint_aware_config(base,nominal,.20);
calibration=bed_supported_v1_calibrate_hip_height(nominal,config);
plan=hybrid_tube_v1_build_plan(nominal,config);
all_cases=dynamic_robust_v1_oracle_case_set(nominal);indices=[1,3,4];
results=cell(1,3);records=[];initializations=cell(1,3);
for local_index=1:3
    item=all_cases(indices(local_index));name=item.case_name;
    case_config=config;case_config.case_name="r3c_"+name;
    initializations{local_index}=dynamic_robust_v1_initial_admissibility( ...
        nominal,item.plant_parameters,calibration,case_config, ...
        item.controller_model_parameters);
    results{local_index}=simulate_dynamic_robust_load_transfer_v1( ...
        case_config,nominal,item.plant_parameters,plan,calibration, ...
        initializations{local_index},item.controller_model_parameters);
    row=r3c_case_record(name,"oracle",results{local_index});
    if isempty(records),records=row;else,records(end+1)=row;end %#ok<AGROW>
    case_dir=fullfile(output_dir,char(name));mkdir(case_dir);
    result=results{local_index};initialization=initializations{local_index}; %#ok<NASGU>
    save(fullfile(case_dir,'result.mat'),'result','initialization','item','-v7.3');
    r3c_create_artifacts(result,case_dir,name=="oracle_moderate");
    fprintf(['ORACLE %s status=%s t=%.3f s=%.6f q2clear=%.6gdeg ' ...
        'soft=%d force=%d interventions=%.3fs states=%s\n'],name, ...
        row.classification,row.duration_s,row.progress, ...
        row.min_q2_soft_clearance_deg,row.soft_limit_samples, ...
        row.force_violation_samples,row.total_intervention_time_s, ...
        row.safety_sequence);
end
moderate=records(2);
nominal_record=records(1);
stage2_permitted=nominal_record.classification=="TASK_COMPLETE" && ...
    nominal_record.soft_limit_samples==0 && ...
    nominal_record.rom_violation_samples==0 && ...
    nominal_record.force_violation_samples==0 && ...
    moderate.soft_limit_samples==0 && ...
    moderate.rom_violation_samples==0 && moderate.force_violation_samples==0 && ...
    moderate.classification~="SOFT_LIMIT_VIOLATION";
save(fullfile(output_dir,'formal_oracle_gate.mat'),'results','records', ...
    'initializations','all_cases','indices','nominal','base','config', ...
    'calibration','plan','stage2_permitted','-v7.3');
writetable(struct2table(records),fullfile(output_dir,'case_metrics.csv'));
file=fopen(fullfile(output_dir,'stage1_gate.txt'),'w');cleanup2=onCleanup(@()fclose(file));
fprintf(file,['nominal_classification=%s\nmoderate_classification=%s\n' ...
    'moderate_soft_samples=%d\n' ...
    'moderate_rom_samples=%d\nmoderate_force_samples=%d\n' ...
    'stage2_permitted=%d\n'],nominal_record.classification, ...
    moderate.classification, ...
    moderate.soft_limit_samples,moderate.rom_violation_samples, ...
    moderate.force_violation_samples,stage2_permitted);
fprintf('R3C STAGE 1 GATE stage2_permitted=%d\n',stage2_permitted);
end
