function run_r3b_recontact_margin_review(run_id)
%RUN_R3B_RECONTACT_MARGIN_REVIEW Offline-only review of one formal output.

if nargin<1,run_id='20260816_141525';end
runner_dir=fileparts(mfilename('fullpath'));
repo_root=fileparts(fileparts(fileparts(runner_dir)));
output_dir=fullfile(repo_root,'linkage','results','local', ...
    'r3b_recontact_margin_controller',run_id);
source=fullfile(output_dir,'formal_r3b_results.mat');
before=dir(source);loaded=load(source,'results','names', ...
    'old_r2b_path','old_r2a_path');
record_cells=cell(numel(loaded.results),1);
for index=1:numel(loaded.results)
    metrics=r3b_recontact_metrics(loaded.results{index});
    metrics.case_name=loaded.names(index);
    metrics.minimum_soft_clearance_deg= ...
        loaded.results{index}.metrics.min_soft_zone_clearance_deg;
    metrics.recontact_soft_samples=sum( ...
        loaded.results{index}.soft_limit_active & ...
        loaded.results{index}.mode=="RECONTACT");
    metrics.load_return_soft_samples=sum( ...
        loaded.results{index}.soft_limit_active & ...
        loaded.results{index}.mode=="LOAD_RETURN");
    metrics.bed_return_soft_samples=sum( ...
        loaded.results{index}.soft_limit_active & ...
        loaded.results{index}.mode=="BED_SUPPORTED_RETURN");
    [metrics.recontact_plateau_force_N, ...
        metrics.recontact_plateau_force_slope_N_s]= ...
        plateau(loaded.results{index});
    record_cells{index}=metrics;
end
records=vertcat(record_cells{:});
writetable(struct2table(records),fullfile(output_dir, ...
    'reviewed_case_metrics.csv'));
file=fopen(fullfile(output_dir,'review_summary.txt'),'w');assert(file>=0);
cleanup=onCleanup(@()fclose(file));
fprintf(file,'R3B offline review; no trajectory rerun.\n');
for index=1:numel(records)
    r=records(index);fprintf(file,[ ...
        '%s %s: recontact peak %.9g N, plateau %.9g N, slope %.9g N/s, ' ...
        'penetration max %.9g m, global bed %.9g N/global penetration ' ...
        '%.9g m, soft total/contact/return/bed-return %d/%d/%d/%d, ' ...
        'min soft clearance %.9g deg\n'],r.case_name,r.classification, ...
        r.peak_bed_force_N,r.recontact_plateau_force_N, ...
        r.recontact_plateau_force_slope_N_s,r.maximum_penetration_m, ...
        r.global_peak_bed_force_N,r.global_maximum_penetration_m, ...
        r.soft_limit_samples,r.recontact_soft_samples, ...
        r.load_return_soft_samples,r.bed_return_soft_samples, ...
        r.minimum_soft_clearance_deg);
end
after=dir(source);
assert(before.bytes==after.bytes && before.datenum==after.datenum, ...
    'R3B review mutated the formal MAT source.');
old_r2b=load(loaded.old_r2b_path,'results');
old_r2a=load(loaded.old_r2a_path,'results');
r3b_recontact_create_artifacts(loaded.results,loaded.names, ...
    old_r2b.results{2},old_r2a.results{2},output_dir,false);
end


function [mean_force,slope]=plateau(result)
indices=find(result.mode=="RECONTACT");
if isempty(indices),mean_force=NaN;slope=NaN;return;end
count=min(numel(indices),round(1/result.config.dt));
indices=indices(end-count+1:end);time=result.t(indices);
force=result.bed_force_N(indices);mean_force=mean(force);
if numel(indices)>1
    fit=polyfit(time-time(1),force,1);slope=fit(1);
else
    slope=NaN;
end
end
