#!/usr/bin/env python3
"""Postprocess exactly the saved 120/120 rigid/P1 pair; no simulation."""
import csv, hashlib, json, subprocess, sys
from pathlib import Path
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

REPO=Path(__file__).resolve().parents[3]
STAGE=REPO/'stages/stage4_adaptive_control'
sys.path[:0]=[str(STAGE/'scripts'),str(STAGE/'src'),str(REPO/'stages/stage3_full3d/src')]
import run_progressive_120_120_ab as runner
from traction_mpc_stage4.cuff_allocator import sagittal_allocation_matrix,sagittal_null_vector,sagittal_wrench_to_world_matrix
ROOT=STAGE/'results/engineering_validation/progressive_120_120_ab_20260907_v1'
SPEC=STAGE/'docs/PROGRESSIVE_120_120_AB_SPEC.json';DOC=SPEC.with_suffix('.md')
TOL=0.06896926724078867

def load(path):
 with np.load(path,allow_pickle=False) as z:return {k:z[k] for k in z.files}
def read(path):return json.loads(Path(path).read_text())
def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def norm(x):return np.linalg.norm(x,axis=1) if np.asarray(x).ndim>1 else abs(np.asarray(x))
def rms_vector(x):return float(np.sqrt(np.mean(norm(np.asarray(x))**2)))
def clean(x):
 if isinstance(x,dict):return {str(k):clean(v) for k,v in x.items()}
 if isinstance(x,(list,tuple)):return [clean(v) for v in x]
 if isinstance(x,np.ndarray):return clean(x.tolist())
 if isinstance(x,np.generic):return clean(x.item())
 if isinstance(x,float) and not np.isfinite(x):return None
 return x
def nearest(t,x):return int(np.argmin(abs(t-x)))
def table(headers,rows):
 def f(v):
  if v is None:return 'n/a'
  if isinstance(v,float):return f'{v:.6g}'
  if isinstance(v,list):return '['+', '.join(f(a) for a in v)+']'
  return str(v)
 return '\n'.join(['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(f(v) for v in row)+' |' for row in rows])

def return_timing(result):
 leg=(result['planned_reference_duration_s']-3.5)/2
 return leg,2.5+leg,2.5+2*leg

def summarize_arm(arm):
 rid=f'hip120_knee120_{arm}_dt0250us';path=ROOT/rid
 r=read(path/'result.json');z=load(path/'trace.npz');m=load(path/'mechanics.npz');md=load(path/'modes.npz');c=load(path/'commands.npz')
 phase=z['reference_phase_time_s'];q=z['human_q_deg_god_view'];ref=z['human_q_ref_deg'];leg,return_start,return_end=return_timing(r)
 frac=(q-np.array([5.,10.]))/(np.array([120.,120.])-np.array([5.,10.]))
 physical_joint_peak=np.max(frac,axis=0)*100
 physical_sync_peak=float(np.max(np.min(frac,axis=1))*100)
 ce=z['control_estimated_state'];cq=np.degrees(ce[:,:2]);cdq=np.degrees(ce[:,2:]);tq=np.degrees(z['control_true_q_rad_god_view']);tdq=np.degrees(z['control_true_dq_rad_s_god_view'])
 qerr=cq-tq;dqerr=cdq-tdq
 mode=md['mode'].astype(str);br=np.flatnonzero(mode=='BRAKE');status=md['decision_status'].astype(str);fi=np.flatnonzero(status=='BRAKE_INFEASIBLE')
 inter=z['safety_filter_intervention_coordinate_norm']
 mt=m['time_s'];acc=np.diff(m['velocity_H'],axis=0)/np.diff(mt)[:,None];at=.5*(mt[1:]+mt[:-1]);jerk=np.diff(acc,axis=0)/np.diff(at)[:,None];jt=.5*(at[1:]+at[:-1])
 p1=None
 if arm=='P1':
  growth=read(path/'growth_windows.json');mask=mt>=max(0.,mt[-1]-.2)
  p1=dict(translation_peak_mm=r['deformation_peak_mm'],translation_rms_mm=float(1000*np.sqrt(np.mean(norm(m['deformation_H'])**2))),rotation_peak_deg=r['rotation_peak_deg'],rotation_rms_deg=float(np.degrees(np.sqrt(np.mean(norm(m['rotation_vector_H'])**2)))),relative_velocity_peak_m_s=float(max(norm(m['relative_velocity_H']))),relative_angular_velocity_peak_rad_s=float(max(norm(m['relative_angular_velocity_H']))),stored_energy_peak_j=r['energy']['stored_peak_j'],damping_loss_j=r['energy']['damping_loss_j'],net_port_work_j=r['energy']['net_port_work_j'],max_abs_energy_residual_j=r['energy']['max_abs_residual_j'],max_abs_energy_residual_ratio=r['energy']['max_abs_residual_ratio'],max_positive_energy_residual_j=r['energy']['max_positive_residual_j'],max_positive_energy_residual_ratio=r['energy']['max_positive_residual_ratio'],final_energy_residual_j=float(m['energy_residual'][-1]),trailing_200ms_residual_slope_w=float(np.polyfit(mt[mask],m['energy_residual'][mask],1)[0]),growth_trigger_count=int(sum(w['stop_reason'] is not None for w in growth)),power_identity_peak_w=r['energy']['max_power_identity_w'],minimum_damping_power_w=r['energy']['minimum_damping_power_w'],numerical_qualification='FAIL_PRESERVED_NOT_REQUALIFIED')
 return dict(run_id=rid,formal_classification=r['task'],termination_reason=r['termination_reason'],reference_completed=r['reference_completed'],physical_time_s=r['simulated_duration_s'],reference_phase_s=r['reference_phase_s'],outbound_reference_percent=float(100*np.clip((phase.max()-1)/leg,0,1)),return_reference_percent=float(100*np.clip((phase.max()-return_start)/leg,0,1)),physical_outbound_sync_peak_percent=physical_sync_peak,physical_outbound_joint_peak_percent=physical_joint_peak.tolist(),human_target_reached=bool(r['endpoint_error_deg'] is not None and r['endpoint_error_deg']<=TOL),human_return_reached=bool(phase.max()>=return_end and r['return_error_deg']<=TOL),maximum_q_deg=np.max(q,axis=0).tolist(),terminal_q_deg=q[-1].tolist(),endpoint_error_deg=r['endpoint_error_deg'],terminal_error_from_initial_deg=r['return_error_deg'],tracking_rmse_deg=r['tracking_rmse_deg'],tracking_max_norm_deg=float(max(norm(q-ref))),state_proxy=dict(q_rmse_deg=np.sqrt(np.mean(qerr**2,axis=0)).tolist(),q_peak_abs_deg=np.max(abs(qerr),axis=0).tolist(),dq_rmse_deg_s=np.sqrt(np.mean(dqerr**2,axis=0)).tolist(),dq_peak_abs_deg_s=np.max(abs(dqerr),axis=0).tolist()),safety=dict(brake_transitions=r['brake']['transition_count'],brake_cycles=r['brake']['brake_cycle_count'],first_brake_time_s=(float(md['time_s'][br[0]]) if len(br) else None),filter_infeasible_count=int(len(fi)),no_safe_action_count=r['no_safe_action_count'],filter_status_counts=r['brake']['safety_filter_status_counts'],filter_intervention_count=int(np.count_nonzero(inter>1e-12)),filter_intervention_peak=float(max(inter)) if len(inter) else None,minimum_feasible_candidates=int(min(md['feasible_candidate_count']))),force=dict(command_rms_n=r['command_force_n']['rms'],command_peak_n=r['command_force_n']['peak'],physical_rms_n=r['physical_force_n']['rms'],physical_peak_n=r['physical_force_n']['peak'],physical_slew_rms_n_s=r['rates']['physical_force_n_s']['rms'],physical_slew_peak_n_s=r['rates']['physical_force_n_s']['peak'],moment_rms_nm=r['physical_moment_R_nm']['rms'],moment_peak_nm=r['physical_moment_R_nm']['peak'],moment_slew_peak_nm_s=r['rates']['physical_moment_nm_s']['peak'],engineering_contract=r['force_contract']['classification'],mechanical_classification=r['force_contract']['mechanical_classification'],strict_contract=r['strict_force_contract']['classification'],force_events=r['force_contract']['events']),human_cuff=dict(acceleration_rms_m_s2=r['motion']['human_cuff']['acceleration']['rms'],acceleration_peak_m_s2=r['motion']['human_cuff']['acceleration']['peak'],acceleration_peak_time_s=float(at[np.argmax(norm(acc))]),jerk_rms_m_s3=r['motion']['human_cuff']['jerk']['rms'],jerk_peak_m_s3=r['motion']['human_cuff']['jerk']['peak'],jerk_peak_time_s=float(jt[np.argmax(norm(jerk))])),p1=p1,warning_count=r['warning_count'],human_rom_event=r['human_rom_event'],raw_result=r)

def null_geometry(q):
 n=sagittal_null_vector(q,runner.base.HIGH_ROM_HUMAN);w=sagittal_wrench_to_world_matrix(q,runner.base.HIGH_ROM_HUMAN)@n;d=w[:3]/np.linalg.norm(w[:3]);B=sagittal_allocation_matrix(q,runner.base.HIGH_ROM_HUMAN)
 return n,w,d,float(np.linalg.cond(B))
def min_force(force,d):
 p=float(force@d);return float(np.linalg.norm(force-p*d)),-p

def rigid_mechanism(rigid):
 rid=rigid['run_id'];path=ROOT/rid;z=load(path/'trace.npz');md=load(path/'modes.npz');c=load(path/'commands.npz');res=rigid['raw_result']
 fi=np.flatnonzero(z['safety_filter_status'].astype(str)=='FILTER_INFEASIBLE');assert len(fi)==1
 ei=int(fi[0]);pi=ei-1;te=float(z['safety_filter_time_s'][ei]);tp=float(z['safety_filter_time_s'][pi])
 cie=nearest(z['control_time_s'],te);cip=nearest(z['control_time_s'],tp);qe=z['control_estimated_state'][cie,:2];qp=z['control_estimated_state'][cip,:2]
 npv,wp,dp,condp=null_geometry(qp);nev,we,de,conde=null_geometry(qe)
 kp=nearest(c['time_s'],tp);lam=float(z['safety_filter_lambda'][pi]);filtered_total=c['force'][kp];nominal_prev=filtered_total-lam*dp
 api=min(int(np.searchsorted(z['time_s'],tp+1e-8)),len(z['time_s'])-1);filtered_alloc=z['allocated_wrench_world'][api];nominal_alloc_prev=filtered_alloc-lam*wp
 last=res['brake']['last_safety_filter'];nominal_event=np.asarray(last['nominal_force_total_n']);nominal_alloc_event=np.asarray(last['nominal_wrench_world'])
 mp,bp=min_force(nominal_prev,dp);me,be=min_force(nominal_event,de)
 fbp=nominal_prev-nominal_alloc_prev[:3];fbe=nominal_event-nominal_alloc_event[:3]
 modei=nearest(md['time_s'],te);updates=np.flatnonzero((md['time_s']<=te)&(md['mpc_status'].astype(str)!='NO_NEW_MPC'));last_update=float(md['time_s'][updates[-1]]) if len(updates) else None
 total_change=nominal_event-nominal_prev;alloc_change=nominal_alloc_event[:3]-nominal_alloc_prev[:3];feedback_change=fbe-fbp
 same=bool(mp<=200+1e-6 and me>200 and np.linalg.norm(feedback_change)>np.linalg.norm(alloc_change))
 return clean(dict(event_time_s=te,previous_time_s=tp,reference_phase_s=float(np.interp(te,z['time_s'],z['reference_phase_time_s'])),outbound_reference_percent=rigid['outbound_reference_percent'],q_event_deg=np.degrees(qe),dq_event_deg_s=np.degrees(z['control_estimated_state'][cie,2:]),q_change_deg=np.degrees(qe-qp),dq_change_deg_s=np.degrees(z['control_estimated_state'][cie,2:]-z['control_estimated_state'][cip,2:]),human_B_condition_previous=condp,human_B_condition_event=conde,null_direction_change_deg=float(np.degrees(np.arccos(np.clip(dp@de,-1,1)))),nominal_force_previous_n=nominal_prev,nominal_force_event_n=nominal_event,nominal_force_change_n=total_change,nominal_force_norm_previous_n=float(np.linalg.norm(nominal_prev)),nominal_force_norm_event_n=float(np.linalg.norm(nominal_event)),minimum_achievable_force_previous_n=mp,minimum_achievable_force_event_n=me,best_lambda_previous=bp,best_lambda_event=be,applied_lambda_previous=lam,allocator_force_previous_n=nominal_alloc_prev[:3],allocator_force_event_n=nominal_alloc_event[:3],allocator_force_change_n=alloc_change,feedback_force_previous_n=fbp,feedback_force_event_n=fbe,feedback_force_change_n=feedback_change,feedback_change_norm_n=float(np.linalg.norm(feedback_change)),allocator_change_norm_n=float(np.linalg.norm(alloc_change)),event_decision_status=str(md['decision_status'][modei]),event_feasible_candidate_count=int(md['feasible_candidate_count'][modei]),last_cem_update_time_s=last_update,mpc_status_at_event=str(md['mpc_status'][modei]),same_mechanism_as_40_80=same,mechanism_statement='feedback-dominated nominal wrench change makes torque-preserving minimum achievable force exceed 200 N' if same else 'not established'))

def path_comparison(mechanism):
 q=np.radians(mechanism['q_event_deg']);rows={}
 for label,rel in [('40_80','progressive_40_80_ab_20260907_v1/hip40_knee80_rigid_dt0250us'),('90_120','progressive_90_120_ab_20260907_v1/hip90_knee120_rigid_dt0250us')]:
  path=STAGE/'results/engineering_validation'/rel;z=load(path/'trace.npz');r=read(path/'result.json');leg,rs,_=return_timing(r);idx=np.flatnonzero(z['control_time_s']>=rs);states=z['control_estimated_state'][idx];dist=np.linalg.norm(states[:,:2]-q,axis=1);i=int(idx[np.argmin(dist)]);tt=float(z['control_time_s'][i]);sf=nearest(z['safety_filter_time_s'],tt)
  rows[label]=dict(nearest_return_time_s=tt,q_est_deg=np.degrees(z['control_estimated_state'][i,:2]).tolist(),dq_est_deg_s=np.degrees(z['control_estimated_state'][i,2:]).tolist(),q_distance_deg=float(np.degrees(min(dist))),filter_status=str(z['safety_filter_status'][sf]),nominal_force_norm_n=float(z['safety_filter_nominal_executable_force_norm_n'][sf]),mode='BRAKE' if label=='40_80' and tt>=11.935 else 'TRACK')
 return dict(rigid_120_120_return_path_available=False,reason='rigid 120/120 terminated during outbound before target and return phases',event_phase='outbound',event_q_deg=mechanism['q_event_deg'],comparison_to_prior_return_paths=rows,interpretation='The same force-feasibility mechanism recurs at a different outbound state; saved 120/120 evidence cannot test whether its return path would reproduce the 40/80 boundary.')

def history(current):
 d40r=read(STAGE/'results/engineering_validation/progressive_relaxed_ab_20260905_v1/hip40_knee40_rigid_dt0250us/result.json');d40p=read(STAGE/'results/engineering_validation/progressive_relaxed_ab_20260905_v1/hip40_knee40_P1_dt0250us/result.json')
 d80=read(STAGE/'results/engineering_validation/progressive_40_80_ab_20260907_v1/detailed_metrics.json');d90=read(STAGE/'results/engineering_validation/progressive_90_120_ab_20260907_v1/detailed_metrics.json')
 return [
  dict(point='40/40',rigid_formal=d40r['task'],p1_formal=d40p['task'],rigid_progress='100/100',p1_progress='100/100',rigid_brake=d40r['brake']['transition_count'],p1_brake=d40p['brake']['transition_count'],rigid_tracking_rmse=d40r['tracking_rmse_deg'],p1_tracking_rmse=d40p['tracking_rmse_deg'],rigid_physical_peak=d40r['physical_force_n']['peak'],p1_physical_peak=d40p['physical_force_n']['peak'],rigid_return_error=d40r['return_error_deg'],p1_return_error=d40p['return_error_deg']),
  dict(point='40/80',rigid_formal=d80['rigid']['formal_classification'],p1_formal=d80['P1']['formal_classification'],rigid_progress='100/100',p1_progress='100/100',rigid_brake=d80['rigid']['safety']['brake_transition_count'],p1_brake=d80['P1']['safety']['brake_transition_count'],rigid_tracking_rmse=d80['rigid']['tracking_rmse_deg'],p1_tracking_rmse=d80['P1']['tracking_rmse_deg'],rigid_physical_peak=d80['rigid']['force']['physical']['peak'],p1_physical_peak=d80['P1']['force']['physical']['peak'],rigid_return_error=d80['rigid']['return_error_deg'],p1_return_error=d80['P1']['return_error_deg']),
  dict(point='90/120',rigid_formal=d90['rigid']['formal_classification'],p1_formal=d90['P1']['formal_classification'],rigid_progress='100/100',p1_progress='100/100',rigid_brake=d90['rigid']['safety']['brake_transition_count'],p1_brake=d90['P1']['safety']['brake_transition_count'],rigid_tracking_rmse=d90['rigid']['tracking_rmse_deg'],p1_tracking_rmse=d90['P1']['tracking_rmse_deg'],rigid_physical_peak=d90['rigid']['force']['physical']['peak'],p1_physical_peak=d90['P1']['force']['physical']['peak'],rigid_return_error=d90['rigid']['return_error_deg'],p1_return_error=d90['P1']['return_error_deg']),
  dict(point='120/120',rigid_formal=current['rigid']['formal_classification'],p1_formal=current['P1']['formal_classification'],rigid_progress=f"{current['rigid']['outbound_reference_percent']:.2f}/0",p1_progress=f"{current['P1']['outbound_reference_percent']:.2f}/0",rigid_brake=current['rigid']['safety']['brake_transitions'],p1_brake=current['P1']['safety']['brake_transitions'],rigid_tracking_rmse=current['rigid']['tracking_rmse_deg'],p1_tracking_rmse=current['P1']['tracking_rmse_deg'],rigid_physical_peak=current['rigid']['force']['physical_peak_n'],p1_physical_peak=current['P1']['force']['physical_peak_n'],rigid_return_error=current['rigid']['terminal_error_from_initial_deg'],p1_return_error=current['P1']['terminal_error_from_initial_deg'])]

def plots(metrics,mechanism,pathcmp):
 fig,axes=plt.subplots(5,2,figsize=(14,15),layout='constrained')
 for col,arm in enumerate(['rigid','P1']):
  rid=metrics[arm]['run_id'];z=load(ROOT/rid/'trace.npz');m=load(ROOT/rid/'mechanics.npz');md=load(ROOT/rid/'modes.npz');c=load(ROOT/rid/'commands.npz');t=z['time_s'];mt=m['time_s'];at=.5*(mt[1:]+mt[:-1]);acc=np.diff(m['velocity_H'],axis=0)/np.diff(mt)[:,None]
  axes[0,col].plot(t,z['human_q_ref_deg'][:,0],'--',label='hip ref');axes[0,col].plot(t,z['human_q_ref_deg'][:,1],'--',label='knee ref');axes[0,col].plot(t,z['human_q_deg_god_view'][:,0],label='hip true');axes[0,col].plot(t,z['human_q_deg_god_view'][:,1],label='knee true');axes[0,col].set_ylabel('angle deg')
  axes[1,col].plot(mt,norm(m['force_R_world']),label='physical F');axes[1,col].step(c['time_s'],norm(c['force']),where='post',label='command F');axes[1,col].axhline(200,color='black',ls=':');axes[1,col].set_ylabel('force N')
  axes[2,col].plot(mt,norm(m['moment_R_world']),label='physical moment');axes[2,col].set_ylabel('moment Nm')
  axes[3,col].plot(at,norm(acc),label='cuff accel');axes[3,col].plot(z['time_s'],norm(z['estimated_human_q_deg']-z['human_q_deg_god_view']),label='q proxy error');axes[3,col].set_ylabel('m/s2 or deg')
  axes[4,col].step(md['time_s'],(md['mode'].astype(str)=='BRAKE').astype(float),where='post',label='BRAKE');axes[4,col].plot(z['safety_filter_time_s'],z['safety_filter_intervention_coordinate_norm']/100,label='filter correction/100');axes[4,col].set_ylabel('mode/scaled filter');axes[4,col].set_xlabel('physical time s')
  for ax in axes[:,col]:ax.grid(alpha=.2);ax.legend(fontsize=7)
  axes[0,col].set_title(arm)
 fig.suptitle('120/120 matched exploratory prefixes — both terminated during outbound')
 fig.savefig(ROOT/'aligned_120_120_diagnostics.png',dpi=160);plt.close(fig)

 rid=metrics['rigid']['run_id'];z=load(ROOT/rid/'trace.npz');m=load(ROOT/rid/'mechanics.npz');md=load(ROOT/rid/'modes.npz');c=load(ROOT/rid/'commands.npz');center=mechanism['event_time_s'];half=.25
 fig,axes=plt.subplots(5,1,figsize=(12,13),sharex=True,layout='constrained');mask=(z['time_s']>=center-half)&(z['time_s']<=center+half);cm=(c['time_s']>=center-half)&(c['time_s']<=center+half);mm=(m['time_s']>=center-half)&(m['time_s']<=center+half);dm=(md['time_s']>=center-half)&(md['time_s']<=center+half);sf=(z['safety_filter_time_s']>=center-half)&(z['safety_filter_time_s']<=center+half)
 x=z['time_s'][mask]-center;axes[0].plot(x,z['estimated_human_q_deg'][mask,0],label='hip proxy');axes[0].plot(x,z['estimated_human_q_deg'][mask,1],label='knee proxy');axes[0].plot(x,z['human_q_ref_deg'][mask,0],'--',label='hip ref');axes[0].plot(x,z['human_q_ref_deg'][mask,1],'--',label='knee ref');axes[0].set_ylabel('angle deg')
 ct=c['time_s'][cm]-center;axes[1].plot(ct,c['force'][cm,0],label='command Fx');axes[1].plot(ct,c['force'][cm,2],label='command Fz');axes[1].set_ylabel('command N')
 mt=m['time_s'][mm]-center;axes[2].plot(mt,m['force_R_world'][mm,0],label='physical Fx');axes[2].plot(mt,m['force_R_world'][mm,2],label='physical Fz');axes[2].set_ylabel('physical N')
 st=z['safety_filter_time_s'][sf]-center;axes[3].plot(st,z['safety_filter_nominal_executable_force_norm_n'][sf],label='nominal |F|');axes[3].plot(st,z['safety_filter_filtered_executable_force_norm_n'][sf],label='filtered |F|');axes[3].axhline(200,color='black',ls=':');axes[3].set_ylabel('force norm N')
 axes[4].step(md['time_s'][dm]-center,(md['mode'][dm].astype(str)=='BRAKE').astype(float),where='post',label='BRAKE');axes[4].plot(st,z['safety_filter_lambda'][sf]/100,label='lambda/100');axes[4].set_ylabel('mode/scaled lambda');axes[4].set_xlabel('time relative to FILTER_INFEASIBLE s')
 for ax in axes:ax.axvline(0,color='red',ls='--');ax.grid(alpha=.2);ax.legend(fontsize=8)
 fig.suptitle('Rigid 120/120 critical window')
 fig.savefig(ROOT/'rigid_120_120_brake_mechanism.png',dpi=170);plt.close(fig)

 fig,ax=plt.subplots(figsize=(9,7))
 for label,rel,color in [('40/80 return','progressive_40_80_ab_20260907_v1/hip40_knee80_rigid_dt0250us','tab:blue'),('90/120 return','progressive_90_120_ab_20260907_v1/hip90_knee120_rigid_dt0250us','tab:green')]:
  p=STAGE/'results/engineering_validation'/rel;z=load(p/'trace.npz');r=read(p/'result.json');leg,rs,_=return_timing(r);idx=z['control_time_s']>=rs;q=np.degrees(z['control_estimated_state'][idx,:2]);ax.plot(q[:,0],q[:,1],label=label,color=color,alpha=.75)
 z=load(ROOT/metrics['rigid']['run_id']/'trace.npz');q=np.degrees(z['control_estimated_state'][:,:2]);ax.plot(q[:,0],q[:,1],label='120/120 rigid outbound prefix',color='tab:red');ax.scatter(*mechanism['q_event_deg'],color='black',s=55,label='120/120 FILTER_INFEASIBLE');old=read(STAGE/'results/engineering_validation/rigid_return_mechanism_audit_20260907_v1/critical_window_metrics.json');ax.scatter(*old['samples']['40_event']['q_est_deg'],marker='x',s=80,label='40/80 first BRAKE');ax.set(xlabel='hip q proxy deg',ylabel='knee q proxy deg',title='Saved state paths: 120/120 ended before return');ax.grid(alpha=.25);ax.legend();fig.tight_layout();fig.savefig(ROOT/'cross_trajectory_state_paths.png',dpi=170);plt.close(fig)

def main():
 s=read(SPEC);reg=read(ROOT/'registration.json');assert sha(SPEC)==sha(ROOT/SPEC.name)==reg['spec_sha'];assert sha(DOC)==sha(ROOT/DOC.name)==reg['md_sha'];assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=REPO,text=True).strip()==s['head'];assert not subprocess.check_output(['git','diff','--name-only','HEAD'],cwd=REPO,text=True).strip()
 for p,h in {**s['frozen_hashes'],**reg['implementation_hashes']}.items():assert sha(REPO/p)==h,p
 metrics={a:summarize_arm(a) for a in ['rigid','P1']};started=[read(ROOT/metrics[a]['run_id']/'started.json') for a in ['rigid','P1']];assert started[0]['pid']!=started[1]['pid']
 ia=load(ROOT/metrics['rigid']['run_id']/'initial_state.npz');ib=load(ROOT/metrics['P1']['run_id']/'initial_state.npz');[np.testing.assert_array_equal(ia[k],ib[k]) for k in ia]
 ca=read(ROOT/metrics['rigid']['run_id']/'run_config.json');cb=read(ROOT/metrics['P1']['run_id']/'run_config.json');assert {k:v for k,v in ca.items() if k!='candidate'}=={k:v for k,v in cb.items() if k!='candidate'}
 mechanism=rigid_mechanism(metrics['rigid']);pathcmp=path_comparison(mechanism);hist=history(metrics)
 save_metrics={a:{k:v for k,v in metrics[a].items() if k!='raw_result'} for a in metrics};payload=clean(dict(spec_sha=reg['spec_sha'],checkpoint=s['head'],metrics=save_metrics,rigid_brake_mechanism=mechanism,path_comparison=pathcmp,history=hist,strict_numerical_qualification='FAIL_PRESERVED',new_runs=2,additional_trajectories=0))
 (ROOT/'detailed_metrics.json').write_text(json.dumps(payload,indent=2,sort_keys=True)+'\n');(ROOT/'rigid_brake_mechanism.json').write_text(json.dumps(mechanism,indent=2,sort_keys=True)+'\n');(ROOT/'cross_trajectory_path_comparison.json').write_text(json.dumps(pathcmp,indent=2,sort_keys=True)+'\n')
 with (ROOT/'comparison.csv').open('w',newline='') as f:
  fields=['arm','formal','termination','outbound_reference_percent','return_reference_percent','physical_outbound_sync_peak_percent','target_reached','return_reached','endpoint_error_deg','terminal_error_from_initial_deg','tracking_rmse_deg','brake','filter_infeasible','no_safe_action','command_rms_n','command_peak_n','physical_rms_n','physical_peak_n','force_slew_peak_n_s','moment_peak_nm','acceleration_peak_m_s2','jerk_peak_m_s3'];w=csv.DictWriter(f,fieldnames=fields);w.writeheader()
  for a in ['rigid','P1']:
   x=metrics[a];w.writerow(dict(arm=a,formal=x['formal_classification'],termination=x['termination_reason'],outbound_reference_percent=x['outbound_reference_percent'],return_reference_percent=x['return_reference_percent'],physical_outbound_sync_peak_percent=x['physical_outbound_sync_peak_percent'],target_reached=x['human_target_reached'],return_reached=x['human_return_reached'],endpoint_error_deg=x['endpoint_error_deg'],terminal_error_from_initial_deg=x['terminal_error_from_initial_deg'],tracking_rmse_deg=x['tracking_rmse_deg'],brake=x['safety']['brake_transitions'],filter_infeasible=x['safety']['filter_infeasible_count'],no_safe_action=x['safety']['no_safe_action_count'],command_rms_n=x['force']['command_rms_n'],command_peak_n=x['force']['command_peak_n'],physical_rms_n=x['force']['physical_rms_n'],physical_peak_n=x['force']['physical_peak_n'],force_slew_peak_n_s=x['force']['physical_slew_peak_n_s'],moment_peak_nm=x['force']['moment_peak_nm'],acceleration_peak_m_s2=x['human_cuff']['acceleration_peak_m_s2'],jerk_peak_m_s3=x['human_cuff']['jerk_peak_m_s3']))
 plots(metrics,mechanism,pathcmp)
 r,p=metrics['rigid'],metrics['P1'];mr=mechanism
 matched_rows=[]
 for label,x in [('Rigid',r),('P1',p)]:matched_rows.append([label,x['formal_classification'],x['termination_reason'],f"{x['outbound_reference_percent']:.2f}/{x['return_reference_percent']:.2f}",x['physical_outbound_sync_peak_percent'],x['human_target_reached'],x['human_return_reached'],x['endpoint_error_deg'],x['terminal_error_from_initial_deg'],x['tracking_rmse_deg'],f"{x['safety']['brake_transitions']}/{x['safety']['filter_infeasible_count']}/{x['safety']['no_safe_action_count']}",f"{x['force']['command_rms_n']:.2f}/{x['force']['command_peak_n']:.2f}",f"{x['force']['physical_rms_n']:.2f}/{x['force']['physical_peak_n']:.2f}",x['force']['physical_slew_peak_n_s'],f"{x['force']['moment_rms_nm']:.2f}/{x['force']['moment_peak_nm']:.2f}",f"{x['human_cuff']['acceleration_rms_m_s2']:.3f}/{x['human_cuff']['acceleration_peak_m_s2']:.3f}",f"{x['human_cuff']['jerk_rms_m_s3']:.1f}/{x['human_cuff']['jerk_peak_m_s3']:.1f}"])
 hist_rows=[[x['point'],x['rigid_formal'],x['p1_formal'],x['rigid_progress'],x['p1_progress'],f"{x['rigid_brake']}/{x['p1_brake']}",f"{x['rigid_tracking_rmse']:.3f}/{x['p1_tracking_rmse']:.3f}",f"{x['rigid_physical_peak']:.2f}/{x['p1_physical_peak']:.2f}",f"{x['rigid_return_error']:.3f}/{x['p1_return_error']:.3f}"] for x in hist]
 report=['# Rigid vs P1 120/120 exploratory matched A/B','',f"Checkpoint `{s['head']}`; Spec SHA256 `{reg['spec_sha']}`. Exactly two fresh processes were run: rigid then registered P1. Both ended during outbound; no additional trajectory was run. The prior strict compliant numerical-qualification FAIL remains unchanged.",'','## Matched metrics',table(['Arm','Formal','Termination','Ref out/return %','Physical outbound %','Target reached','Returned','Endpoint err deg','Terminal-vs-initial deg','Tracking RMSE deg','BRAKE/FILTER_INF/NSA','Command RMS/peak N','Physical RMS/peak N','Force slew peak N/s','Moment RMS/peak Nm','Accel RMS/peak','Jerk RMS/peak'],matched_rows),'',
 'Endpoint error is `n/a` because neither reference reached target hold. The reported terminal-versus-initial error is the frozen `return_error_deg` field evaluated at early outbound termination; it is not evidence that a return was attempted. Physical outbound percentage is the maximum simultaneous minimum of the two normalized joint progresses.','',
 '## Actual completion',f"Rigid executed {r['outbound_reference_percent']:.2f}% of outbound reference and physically reached {r['physical_outbound_sync_peak_percent']:.2f}% simultaneous joint progress before FILTER_INFEASIBLE at {r['physical_time_s']:.3f} s. It neither reached [120,120] nor entered return.",f"P1 executed {p['outbound_reference_percent']:.2f}% of outbound reference and physically reached {p['physical_outbound_sync_peak_percent']:.2f}% simultaneous joint progress before the existing physical-force policy stopped it at {p['physical_time_s']:.3f} s. It neither reached [120,120] nor entered return.",'',
 '## Rigid failure mechanism',f"The same immediate mechanism observed at rigid 40/80 is directly reproduced. From {mr['previous_time_s']:.3f} to {mr['event_time_s']:.3f} s, the torque-preserving minimum achievable force rises {mr['minimum_achievable_force_previous_n']:.3f} -> {mr['minimum_achievable_force_event_n']:.3f} N and crosses the unchanged 200 N gate. The estimated q/dq is unchanged across the measurement-held pair; Human allocation conditioning remains {mr['human_B_condition_event']:.3f} and the null direction change is {mr['null_direction_change_deg']:.6f} deg.",f"Nominal force changes by {mr['nominal_force_change_n']} N. The allocator contribution changes by only {mr['allocator_force_change_n']} N (norm {mr['allocator_change_norm_n']:.3f}), while the derived feedback contribution changes by {mr['feedback_force_change_n']} N (norm {mr['feedback_change_norm_n']:.3f}). At the event no BRAKE candidate is feasible (`feasible_candidate_count=0`), so termination is BRAKE_INFEASIBLE. This supports the same feedback-driven wrench-change -> torque-preserving minimum >200 N mechanism; it does not identify which position/velocity feedback subterm caused the change.",'',
 '## P1 failure and energy',f"P1 avoids FILTER_INFEASIBLE and BRAKE and advances {p['outbound_reference_percent']-r['outbound_reference_percent']:.2f} reference-percentage points farther, but its physical cuff force reaches {p['force']['physical_peak_n']:.3f} N and triggers the registered absolute transient ceiling. Its command remains bounded at {p['force']['command_peak_n']:.3f} N. This is a physical-force-policy failure, not a numerical warning or runaway deformation.",table(['P1 diagnostic','Value'],[['Translation peak/RMS mm',f"{p['p1']['translation_peak_mm']:.6f}/{p['p1']['translation_rms_mm']:.6f}"],['Rotation peak/RMS deg',f"{p['p1']['rotation_peak_deg']:.6f}/{p['p1']['rotation_rms_deg']:.6f}"],['Stored energy peak J',p['p1']['stored_energy_peak_j']],['Damping loss J',p['p1']['damping_loss_j']],['Max abs residual J / ratio',f"{p['p1']['max_abs_energy_residual_j']:.6f}/{100*p['p1']['max_abs_energy_residual_ratio']:.4f}%"],['Max positive residual J / ratio',f"{p['p1']['max_positive_energy_residual_j']:.6f}/{100*p['p1']['max_positive_energy_residual_ratio']:.4f}%"],['Final residual / trailing slope',f"{p['p1']['final_energy_residual_j']:.6f} J / {p['p1']['trailing_200ms_residual_slope_w']:.6f} W"],['Growth watchdog triggers',p['p1']['growth_trigger_count']]]),'Energy remains diagnostic. Zero growth-watchdog triggers and bounded deformation do not requalify P1; the strict numerical-qualification FAIL is preserved.','',
 '## State proxy',table(['Arm','q RMSE hip/knee deg','q peak hip/knee deg','dq RMSE hip/knee deg/s','dq peak hip/knee deg/s'],[[a,metrics[a]['state_proxy']['q_rmse_deg'],metrics[a]['state_proxy']['q_peak_abs_deg'],metrics[a]['state_proxy']['dq_rmse_deg_s'],metrics[a]['state_proxy']['dq_peak_abs_deg_s']] for a in ['rigid','P1']]),'',
 '## Cross-trajectory comparison',table(['Point','Rigid formal','P1 formal','Rigid progress','P1 progress','BRAKE R/P1','Tracking RMSE R/P1','Physical peak R/P1 N','Return/terminal error R/P1 deg'],hist_rows),'',f"Rigid 120/120 terminates during outbound at q={mr['q_event_deg']} deg, {pathcmp['comparison_to_prior_return_paths']['40_80']['q_distance_deg']:.2f} deg from the closest saved 40/80 return state and {pathcmp['comparison_to_prior_return_paths']['90_120']['q_distance_deg']:.2f} deg from the closest 90/120 return state. Those prior matched states remain TRACK at 74.70 N and 68.08 N nominal force, respectively. The same local feasibility mechanism therefore occurs at a different configuration/history, but no 120/120 return path exists to test recurrence on return.",'',
 '## Interpretation','### DIRECTLY OBSERVED','- Rigid: FILTER_INFEASIBLE/BRAKE_INFEASIBLE at 53.99% outbound reference; torque-preserving minimum achievable force is 213.09 N.','- P1: no BRAKE, 58.20% outbound reference, then physical-force absolute transient ceiling at 222.22 N.','- Both runs stop before target and return. Both have zero warnings, finite evidence and no Human ROM event.','',
 '### SUPPORTED BY CURRENT EVIDENCE','- Rigid 120/120 repeats the 40/80 feedback-dominated Safety Filter incompatibility mechanism, despite occurring during outbound at a different state.','- P1 shifts the limiting mechanism from executable-command infeasibility to physical transmitted-force violation and strongly reduces force slew/jerk, but does not rescue the task.','- The boundary remains path/history dependent and non-monotonic across the sampled trajectories: 90/120 stays TRACK throughout, while 40/80 fails on return and 120/120 fails on outbound.','',
 '### UNRESOLVED','- Because 120/120 never reaches return, this pair cannot determine how its return path would compare with 40/80 or 90/120.','- Saved data do not split the derived feedback wrench into position and velocity terms or provide per-candidate CEM winner scores.','- Single executions do not establish repeatability or numerical qualification.','',
 '### NOT SUPPORTED','- A consistent P1 task-completion benefit across trajectories.','- A monotone ROM capability boundary.','- Clinical safety, validated compliance physics, or reversal of the prior strict numerical FAIL.','',
 '## P1 benefit pattern','P1 benefits are trajectory-specific. At 40/80 it prevents rigid BRAKE and restores a near-complete physical return; at 90/120 it reduces force severity but does not change formal completion and worsens return precision; at 120/120 it avoids BRAKE and smooths force slew/jerk but produces a higher physical peak and a hard force-policy stop. At 40/40 it slightly worsens tracking and force peak. The consistent pattern is transient smoothing, not consistent force-peak reduction or task rescue.','',
 '![Aligned diagnostics](aligned_120_120_diagnostics.png)','','![Rigid mechanism](rigid_120_120_brake_mechanism.png)','','![Cross trajectory paths](cross_trajectory_state_paths.png)','',
 '## Reproducibility',f"Fresh process IDs: {started[0]['pid']} and {started[1]['pid']}. Initial states are exact; configs match except interface. Source HEAD and {len(s['frozen_hashes'])} frozen hashes were verified. No controller, P1, Human/robot, geometry, trajectory timing, solver, dt, seed, measurement boundary, force limit, safety stack, or completion tolerance changed.",'Commands: freeze once; `run_progressive_120_120_ab.py --run-next` exactly twice; this postprocessor once. No formal or additional trajectory command is admitted. Results remain uncommitted.']
 (ROOT/'REPORT.md').write_text('\n\n'.join(report)+'\n')
 validation=dict(spec_sha=reg['spec_sha'],md_sha=reg['md_sha'],head=s['head'],executed_runs=2,unique_process_ids=[x['pid'] for x in started],paired_initial_state_exact=True,paired_config_equal_except_interface=True,frozen_hashes_verified=len(s['frozen_hashes']),implementation_hashes_verified=len(reg['implementation_hashes']),postprocessor_sha=sha(Path(__file__)),no_simulation=True,no_additional_trajectory=True,strict_numerical_qualification='FAIL_PRESERVED')
 (ROOT/'postprocess_validation.json').write_text(json.dumps(validation,indent=2,sort_keys=True)+'\n')
 files=sorted(p for p in ROOT.rglob('*') if p.is_file() and p.name!='SHA256SUMS');(ROOT/'SHA256SUMS').write_text('\n'.join(f"{sha(p)}  {p.relative_to(ROOT)}" for p in files)+'\n')
 print(json.dumps(clean(dict(validation=validation,rigid_mechanism=mechanism,summary={a:{k:save_metrics[a][k] for k in ['formal_classification','termination_reason','outbound_reference_percent','return_reference_percent','physical_outbound_sync_peak_percent','human_target_reached','human_return_reached','tracking_rmse_deg']} for a in ['rigid','P1']})),indent=2))
if __name__=='__main__':main()
