function [u, details] = bed_supported_v1_robot_controller( ...
        q, dq, q_ref, dq_ref, ddq_ref, tau_bed, u_previous, p, config, ...
        robot_authority)
%BED_SUPPORTED_V1_ROBOT_CONTROLLER Existing endpoint law with measured bed torque.

q = q(:); dq = dq(:); tau_bed = tau_bed(:); u_previous = u_previous(:);
if nargin < 10, robot_authority = 1; end
if ~isscalar(robot_authority) || robot_authority < 0 || robot_authority > 1
    error('BedSupportedV1:InvalidRobotAuthority', ...
        'robot_authority must be a scalar in [0,1].');
end
mapping = single_arm_v2_force_map(q, dq, p);
[M, h, ~, G] = human_two_link_v2_dynamics_terms(q, dq, p);
passive_dynamic = human_two_link_v2_passive_torque(q, dq, p);
passive_static = human_two_link_v2_passive_torque(q, zeros(2, 1), p);
ddq_feedback = -config.Kp*(q-q_ref)-config.Kd*(dq-dq_ref);
tau_total_desired = G+passive_static+M*ddq_ref+h+ ...
    (passive_dynamic-passive_static)+M*ddq_feedback;
tau_robot_desired = robot_authority*(tau_total_desired-tau_bed);
[u_desired, linear_solve] = single_arm_v2_stable_force_solve( ...
    mapping.A, tau_robot_desired, config.svd_relative_tolerance);

slew_step = config.du_max(:)*config.dt;
lower = max(config.u_min(:), u_previous-slew_step);
upper = min(config.u_max(:), u_previous+slew_step);
B = config.W_tau*mapping.A/config.tau_scale_Nm;
d = config.W_tau*tau_robot_desired/config.tau_scale_Nm;
ref_weight = config.lambda_ref/config.F_scale_N^2;
du_denominator = config.du_scale_N_s*config.dt;
du_weight = config.lambda_du/du_denominator^2;
H = B'*B+(ref_weight+du_weight)*eye(2);
f = -B'*d-ref_weight*u_desired-du_weight*u_previous;
[u, solver] = single_arm_v2_solve_box_qp(H, f, lower, upper);
residual = mapping.A*u-tau_robot_desired;
tol = config.bound_tolerance_N;
details = struct('mapping', mapping, 'M', M, 'h', h, 'G', G, ...
    'tau_bed_Nm', tau_bed, 'tau_total_desired_Nm', tau_total_desired, ...
    'robot_authority', robot_authority, ...
    'tau_robot_desired_Nm', tau_robot_desired, 'u_desired_N', u_desired, ...
    'u_N', u, 'force_rate_N_s', (u-u_previous)/config.dt, ...
    'torque_residual_Nm', residual, ...
    'bounded_feasible', norm(residual) <= config.residual_tolerance_Nm, ...
    'force_saturated', any(abs(u-config.u_min(:)) <= tol | ...
    abs(u-config.u_max(:)) <= tol), ...
    'slew_saturated', any(abs(u-lower) <= tol | abs(u-upper) <= tol), ...
    'effective_lower_N', lower, 'effective_upper_N', upper, ...
    'linear_solve', linear_solve, 'solver', solver);
end
