function robust = bed_supported_v1_robust_hold_point( ...
        q, nominal, uncertainty, component_bounds_N, svd_tolerance)
%BED_SUPPORTED_V1_ROBUST_HOLD_POINT Worst registered quasistatic hold force.

if nargin < 5
    svd_tolerance = 1e-12;
end
nominal_point = bed_supported_v1_force_margin_point(q, nominal, ...
    component_bounds_N, svd_tolerance);
case_count = numel(uncertainty.case_ids);
case_force_norm_inf_N = NaN(case_count, 1);
case_force_local_N = NaN(2, case_count);
case_residual_norm_Nm = NaN(case_count, 1);
for case_index = 1:case_count
    point = bed_supported_v1_force_margin_point(q, ...
        uncertainty.parameters{case_index}, component_bounds_N, ...
        svd_tolerance);
    case_force_norm_inf_N(case_index) = point.force_norm_inf_N;
    case_force_local_N(:, case_index) = point.force_local_N;
    case_residual_norm_Nm(case_index) = ...
        point.exact_torque_residual_norm_Nm;
end
[worst_required_N, worst_index] = max(case_force_norm_inf_N);
if isempty(worst_index) || ~isfinite(worst_required_N)
    worst_index = NaN;
    worst_case_id = "rank_deficient";
    worst_force_local_N = [NaN; NaN];
else
    worst_case_id = uncertainty.case_ids(worst_index);
    worst_force_local_N = case_force_local_N(:, worst_index);
end
robust = struct('q', q(:), 'nominal', nominal_point, ...
    'worst_required_force_N', worst_required_N, ...
    'worst_case_id', worst_case_id, ...
    'worst_case_index', worst_index, ...
    'worst_force_local_N', worst_force_local_N, ...
    'force_margin_N', component_bounds_N(:)'-worst_required_N, ...
    'case_force_norm_inf_N', case_force_norm_inf_N, ...
    'case_force_local_N', case_force_local_N, ...
    'case_residual_norm_Nm', case_residual_norm_Nm);
end
