function study = bed_supported_v1_force_margin_map( ...
        p, tube_caps_deg, component_bounds_N, grid_resolution_deg, ...
        svd_relative_tolerance)
%BED_SUPPORTED_V1_FORCE_MARGIN_MAP Dense initial-tube hold-force diagnostic.

if nargin < 5
    svd_relative_tolerance = 1e-12;
end
tube_caps_deg = tube_caps_deg(:)';
component_bounds_N = component_bounds_N(:)';
if any(~isfinite(tube_caps_deg)) || any(tube_caps_deg <= 0) || ...
        any(~isfinite(component_bounds_N)) || ...
        any(component_bounds_N <= 0) || ...
        ~isscalar(grid_resolution_deg) || ...
        ~isfinite(grid_resolution_deg) || grid_resolution_deg <= 0
    error('BedSupportedV1:InvalidForceMarginMap', ...
        'Tube caps, force bounds, and grid resolution must be valid.');
end

q0_deg = [5; 10];
tube_cells = cell(1, numel(tube_caps_deg));
for tube_index = 1:numel(tube_caps_deg)
    cap_deg = tube_caps_deg(tube_index);
    q1_deg = bounded_grid(q0_deg(1)-cap_deg, ...
        q0_deg(1)+cap_deg, rad2deg(p.q_min(1)), ...
        rad2deg(p.q_max(1)), grid_resolution_deg);
    q2_deg = bounded_grid(q0_deg(2)-cap_deg, ...
        q0_deg(2)+cap_deg, rad2deg(p.q_min(2)), ...
        rad2deg(p.q_max(2)), grid_resolution_deg);
    q2_deg = q2_deg(q2_deg > 0);
    [q1_grid_deg, q2_grid_deg] = meshgrid(q1_deg, q2_deg);
    grid_size = size(q1_grid_deg);

    F_parallel_N = NaN(grid_size);
    F_perp_N = NaN(grid_size);
    force_norm_2_N = NaN(grid_size);
    force_norm_inf_N = NaN(grid_size);
    sigma_min = NaN(grid_size);
    condition_number = NaN(grid_size);
    soft_limit_active = false(grid_size);
    soft_limit_margin_deg = NaN(grid_size);
    exact_torque_residual_norm_Nm = NaN(grid_size);

    for sample_index = 1:numel(q1_grid_deg)
        q = deg2rad([q1_grid_deg(sample_index); ...
            q2_grid_deg(sample_index)]);
        point = bed_supported_v1_force_margin_point( ...
            q, p, component_bounds_N, svd_relative_tolerance);
        F_parallel_N(sample_index) = point.F_parallel_N;
        F_perp_N(sample_index) = point.F_perp_N;
        force_norm_2_N(sample_index) = point.force_norm_2_N;
        force_norm_inf_N(sample_index) = point.force_norm_inf_N;
        sigma_min(sample_index) = point.sigma_min;
        condition_number(sample_index) = point.condition_number;
        soft_limit_active(sample_index) = point.soft_limit_active;
        soft_limit_margin_deg(sample_index) = rad2deg( ...
            point.minimum_soft_limit_margin_rad);
        exact_torque_residual_norm_Nm(sample_index) = ...
            point.exact_torque_residual_norm_Nm;
    end

    force_margin_N = NaN([grid_size, numel(component_bounds_N)]);
    feasible = false([grid_size, numel(component_bounds_N)]);
    robust_feasible = false([grid_size, numel(component_bounds_N)]);
    best_cells = cell(1, numel(component_bounds_N));
    raw_best_cells = cell(1, numel(component_bounds_N));
    eligible = ~soft_limit_active & isfinite(force_norm_inf_N);
    for bound_index = 1:numel(component_bounds_N)
        bound_N = component_bounds_N(bound_index);
        margin = bound_N-force_norm_inf_N;
        exact_mask = margin >= -1e-10;
        robust_mask = exact_mask & eligible;
        force_margin_N(:, :, bound_index) = margin;
        feasible(:, :, bound_index) = exact_mask;
        robust_feasible(:, :, bound_index) = robust_mask;

        [raw_maximum_margin_N, raw_linear_index] = max(margin(:));
        raw_best_cells{bound_index} = struct( ...
            'component_bound_N', bound_N, ...
            'maximum_margin_N', raw_maximum_margin_N, ...
            'q_deg', [q1_grid_deg(raw_linear_index); ...
                q2_grid_deg(raw_linear_index)], ...
            'F_parallel_N', F_parallel_N(raw_linear_index), ...
            'F_perp_N', F_perp_N(raw_linear_index), ...
            'force_norm_2_N', force_norm_2_N(raw_linear_index), ...
            'force_norm_inf_N', force_norm_inf_N(raw_linear_index), ...
            'soft_limit_active', soft_limit_active(raw_linear_index), ...
            'soft_limit_margin_deg', ...
                soft_limit_margin_deg(raw_linear_index));

        candidate_margin = margin;
        candidate_margin(~eligible) = -Inf;
        [maximum_margin_N, linear_index] = max(candidate_margin(:));
        best_cells{bound_index} = struct( ...
            'component_bound_N', bound_N, ...
            'maximum_margin_N', maximum_margin_N, ...
            'q_deg', [q1_grid_deg(linear_index); ...
                q2_grid_deg(linear_index)], ...
            'F_parallel_N', F_parallel_N(linear_index), ...
            'F_perp_N', F_perp_N(linear_index), ...
            'force_norm_2_N', force_norm_2_N(linear_index), ...
            'force_norm_inf_N', force_norm_inf_N(linear_index), ...
            'sigma_min', sigma_min(linear_index), ...
            'condition_number', condition_number(linear_index), ...
            'soft_limit_active', soft_limit_active(linear_index), ...
            'soft_limit_margin_deg', soft_limit_margin_deg(linear_index), ...
            'exact_torque_residual_norm_Nm', ...
                exact_torque_residual_norm_Nm(linear_index), ...
            'feasible_fraction', mean(exact_mask(:)), ...
            'robust_feasible_fraction', mean(robust_mask(:)));
    end

    best = [best_cells{:}];
    raw_best = [raw_best_cells{:}];
    tube_cells{tube_index} = struct( ...
        'cap_deg', cap_deg, ...
        'q1_deg', q1_deg, ...
        'q2_deg', q2_deg, ...
        'q1_grid_deg', q1_grid_deg, ...
        'q2_grid_deg', q2_grid_deg, ...
        'F_parallel_N', F_parallel_N, ...
        'F_perp_N', F_perp_N, ...
        'force_norm_2_N', force_norm_2_N, ...
        'force_norm_inf_N', force_norm_inf_N, ...
        'force_margin_N', force_margin_N, ...
        'sigma_min', sigma_min, ...
        'condition_number', condition_number, ...
        'soft_limit_active', soft_limit_active, ...
        'soft_limit_margin_deg', soft_limit_margin_deg, ...
        'exact_torque_residual_norm_Nm', ...
            exact_torque_residual_norm_Nm, ...
        'feasible', feasible, ...
        'robust_feasible', robust_feasible, ...
        'raw_best', raw_best, ...
        'best', best);
end
tubes = [tube_cells{:}];

study = struct();
study.q0_deg = q0_deg;
study.tube_caps_deg = tube_caps_deg;
study.component_bounds_N = component_bounds_N;
study.grid_resolution_deg = grid_resolution_deg;
study.svd_relative_tolerance = svd_relative_tolerance;
study.parameters = p;
study.tubes = tubes;
end


function values = bounded_grid(requested_lower, requested_upper, ...
        allowed_lower, allowed_upper, step)
lower = max(requested_lower, allowed_lower);
upper = min(requested_upper, allowed_upper);
count = floor((upper-lower)/step+1e-9);
values = lower+(0:count)*step;
if isempty(values) || values(end) < upper-1e-9
    values(end+1) = upper;
end
values = unique(round(values, 10));
end
