"""Single-parameter moving-horizon state/parameter estimators for Spring2D.

This module intentionally implements only the Stage 10B estimators: a joint
state/parameter MHE with either mass or inverse mass as its sole unknown
parameter.  Stiffness and radial damping remain fixed at their nominal values.
"""

from __future__ import annotations

from collections import deque
import time
from typing import Any

import numpy as np
from scipy.optimize import least_squares

from traction_mpc.models.spring2d_dynamics import step_dynamics


class SingleParameterMHE:
    """Single-shooting joint state/parameter MHE over a finite measurement window.

    The decision variables are the state at the start of the current window and
    one static parameter.  All states inside the window are generated by the
    implemented RK4 dynamics, so dynamics are enforced exactly rather than by a
    penalty.  The state and parameter are jointly optimized against the full
    window of measurements plus an arrival prior.
    """

    parameterizations = {"m", "inverse_m"}

    def __init__(self, model_params: dict[str, Any], cfg: dict[str, Any], parameterization: str):
        if parameterization not in self.parameterizations:
            raise ValueError(f"Unsupported MHE parameterization: {parameterization}")
        self.base_model_params = dict(model_params)
        self.cfg = dict(cfg)
        self.parameterization = parameterization
        self.window_size = int(cfg["window_size"])
        self.update_interval = int(cfg["update_interval"])
        self.max_nfev = int(cfg["max_nfev"])
        self.lambda_arrival_state = float(cfg["lambda_arrival_state"])
        self.lambda_arrival_parameter = float(cfg["lambda_arrival_parameter"])
        self.measurement_weights = np.asarray(cfg["measurement_weights"], dtype=float)
        self.arrival_state_scale = np.asarray(cfg["arrival_state_scale"], dtype=float)
        self.mass_scale = float(cfg["mass_scale"])
        self.nominal_mass = float(self.base_model_params["m"])
        self.nominal_k = float(self.base_model_params["k"])
        self.nominal_b_r = float(self.base_model_params["b_r"])
        self.mass_bounds = tuple(float(v) for v in cfg["mass_bounds"])
        self.parameter_scale = self._parameter_scale()
        self.parameter_bounds = self._parameter_bounds()
        self.measurements: deque[np.ndarray] = deque(maxlen=self.window_size + 1)
        self.actions: deque[np.ndarray] = deque(maxlen=self.window_size)
        self.arrival_state: np.ndarray | None = None
        self.parameter_hat = self._parameter_from_mass(self.nominal_mass)
        self.state_hat: np.ndarray | None = None
        self.last_solution: np.ndarray | None = None
        self.last_diagnostics: dict[str, Any] = {}
        self.num_transitions = 0

    def reset(self, initial_measurement: np.ndarray) -> np.ndarray:
        measurement = self._state(initial_measurement)
        self.measurements.clear()
        self.actions.clear()
        self.measurements.append(measurement)
        self.arrival_state = measurement.copy()
        self.parameter_hat = self._parameter_from_mass(self.nominal_mass)
        self.state_hat = measurement.copy()
        self.last_solution = None
        self.last_diagnostics = {"updated": False, "success": True, "status": "reset"}
        self.num_transitions = 0
        return self.state_hat.copy()

    def add_measurement(self, action: np.ndarray, measurement: np.ndarray) -> dict[str, Any]:
        if self.state_hat is None or self.arrival_state is None:
            raise RuntimeError("SingleParameterMHE must be reset before use.")
        action_arr = np.asarray(action, dtype=float)
        measurement_arr = self._state(measurement)
        if len(self.actions) == self.window_size:
            # deque will drop this transition.  Advance the arrival prior by the
            # same transition so it remains aligned with the new window start.
            dropped_action = np.asarray(self.actions[0], dtype=float)
            params = self._physical_params(self.parameter_hat)
            self.arrival_state = step_dynamics(self.arrival_state, dropped_action, float(params["dt"]), params)
            self.arrival_state[2] = max(float(self.arrival_state[2]), 1.0e-6)
        self.actions.append(action_arr.copy())
        self.measurements.append(measurement_arr.copy())
        self.num_transitions += 1

        updated = False
        success = bool(self.last_diagnostics.get("success", True))
        if len(self.actions) >= 1 and self.num_transitions % self.update_interval == 0:
            updated = True
            success = self._solve_window()
        else:
            params = self._physical_params(self.parameter_hat)
            self.state_hat = step_dynamics(self.state_hat, action_arr, float(params["dt"]), params)
            self.state_hat[2] = max(float(self.state_hat[2]), 1.0e-6)
            self.last_diagnostics = {
                **self.last_diagnostics,
                "updated": False,
                "success": success,
                "status": "propagated",
                "solve_time_s": 0.0,
            }
        return {
            "state_hat": self.state_hat.copy(),
            "m_hat": self.mass_hat,
            "parameter_hat": float(self.parameter_hat),
            "updated": updated,
            "success": success,
            "diagnostics": dict(self.last_diagnostics),
        }

    @property
    def mass_hat(self) -> float:
        return self._mass_from_parameter(self.parameter_hat)

    def get_model_params(self) -> dict[str, Any]:
        return self._physical_params(self.parameter_hat)

    def _solve_window(self) -> bool:
        started = time.perf_counter()
        measurements = np.asarray(self.measurements, dtype=float)
        actions = np.asarray(self.actions, dtype=float)
        # The current deque is contiguous: N actions, N+1 measurements.
        if len(measurements) != len(actions) + 1:
            raise RuntimeError("MHE window alignment failure")
        x_prior = np.asarray(self.arrival_state, dtype=float)
        q_prior = float(self.parameter_hat)
        initial_state = measurements[0].copy()
        if self.last_solution is not None and np.all(np.isfinite(self.last_solution[:4])):
            # Reuse the previous arrival state only if it is still near the
            # current window start; otherwise the measurement is safer.
            previous = self.last_solution[:4]
            if np.linalg.norm((previous - initial_state) / self.arrival_state_scale) < 5.0:
                initial_state = previous.copy()
        initial = np.concatenate([initial_state, [q_prior]])
        lower = np.concatenate([np.full(4, -np.inf), [self.parameter_bounds[0]]])
        upper = np.concatenate([np.full(4, np.inf), [self.parameter_bounds[1]]])
        lower[2] = 1.0e-6

        try:
            result = least_squares(
                lambda z: self._residual(z, measurements, actions, x_prior, q_prior),
                initial,
                bounds=(lower, upper),
                max_nfev=self.max_nfev,
                xtol=float(self.cfg["xtol"]),
                ftol=float(self.cfg["ftol"]),
                gtol=float(self.cfg["gtol"]),
            )
            finite = bool(np.all(np.isfinite(result.x)))
            success = bool(result.success and finite)
        except (FloatingPointError, OverflowError, ValueError) as exc:
            result = None
            success = False
            failure_message = f"{type(exc).__name__}: {exc}"

        if success and result is not None:
            x0 = np.asarray(result.x[:4], dtype=float)
            q = float(result.x[4])
            states = self._rollout(x0, actions, q)
            self.state_hat = states[-1].copy()
            # This is the current window's first state.  It is advanced only
            # when deque drops an old transition, keeping it aligned with the
            # moving window instead of advancing it prematurely at each solve.
            self.arrival_state = states[0].copy()
            self.parameter_hat = q
            self.last_solution = np.asarray(result.x, dtype=float).copy()
            jacobian = np.asarray(result.jac, dtype=float)
            information = jacobian.T @ jacobian
            residual = np.asarray(result.fun, dtype=float)
            dof = max(len(residual) - len(result.x), 1)
            covariance = float(np.dot(residual, residual) / dof) * np.linalg.pinv(information, rcond=1.0e-12)
            param_std = float(np.sqrt(max(covariance[-1, -1], 0.0)))
            singular = np.linalg.svd(jacobian, compute_uv=False)
            status = str(result.message)
            nfev = int(result.nfev)
            cost = float(result.cost)
        else:
            # Preserve the previous valid estimate; subsequent steps continue
            # with the same model, making failures explicit in diagnostics.
            jacobian = np.empty((0, 5))
            covariance = np.full((5, 5), np.nan)
            param_std = np.nan
            singular = np.array([], dtype=float)
            status = failure_message if result is None else str(result.message)
            nfev = 0 if result is None else int(result.nfev)
            cost = np.nan if result is None else float(result.cost)

        self.last_diagnostics = {
            "updated": True,
            "success": success,
            "status": status,
            "nfev": nfev,
            "cost": cost,
            "solve_time_s": float(time.perf_counter() - started),
            "window_length": int(len(actions)),
            "parameter_std": param_std,
            "jacobian_rank": int(np.linalg.matrix_rank(jacobian)) if jacobian.size else 0,
            "jacobian_condition": float(np.linalg.cond(jacobian)) if jacobian.size else np.nan,
            "minimum_singular_value": float(np.min(singular)) if singular.size else np.nan,
            "parameter_bound_hit": bool(
                np.isclose(self.parameter_hat, self.parameter_bounds[0])
                or np.isclose(self.parameter_hat, self.parameter_bounds[1])
            ),
        }
        return success

    def _residual(self, decision: np.ndarray, measurements: np.ndarray, actions: np.ndarray, x_prior: np.ndarray, q_prior: float) -> np.ndarray:
        states = self._rollout(decision[:4], actions, float(decision[4]))
        measurement_residual = (states - measurements) * self.measurement_weights
        arrival_state = np.sqrt(self.lambda_arrival_state) * (decision[:4] - x_prior) / self.arrival_state_scale
        arrival_parameter = np.sqrt(self.lambda_arrival_parameter) * (float(decision[4]) - q_prior) / self.parameter_scale
        return np.concatenate([measurement_residual.reshape(-1), arrival_state, [arrival_parameter]])

    def _rollout(self, initial_state: np.ndarray, actions: np.ndarray, parameter: float) -> np.ndarray:
        states = [self._state(initial_state)]
        params = self._physical_params(parameter)
        for action in actions:
            next_state = step_dynamics(states[-1], action, float(params["dt"]), params)
            next_state[2] = max(float(next_state[2]), 1.0e-6)
            states.append(next_state)
        return np.asarray(states, dtype=float)

    def _physical_params(self, parameter: float) -> dict[str, Any]:
        params = dict(self.base_model_params)
        params.update({"m": self._mass_from_parameter(parameter), "k": self.nominal_k, "b_r": self.nominal_b_r})
        return params

    def _parameter_from_mass(self, mass: float) -> float:
        return float(mass if self.parameterization == "m" else 1.0 / mass)

    def _mass_from_parameter(self, parameter: float) -> float:
        return float(parameter if self.parameterization == "m" else 1.0 / parameter)

    def _parameter_bounds(self) -> tuple[float, float]:
        lo, hi = self.mass_bounds
        return (lo, hi) if self.parameterization == "m" else (1.0 / hi, 1.0 / lo)

    def _parameter_scale(self) -> float:
        return self.mass_scale if self.parameterization == "m" else 1.0 / self.mass_scale

    @staticmethod
    def _state(values: np.ndarray) -> np.ndarray:
        state = np.asarray(values, dtype=float).copy()
        if state.shape != (4,) or not np.all(np.isfinite(state)):
            raise ValueError("MHE state/measurement must be a finite vector with shape (4,)")
        state[2] = max(float(state[2]), 1.0e-6)
        return state
