function evaluation = r4_evaluate_setting(anchor,model_kind,support_mode, ...
        family,posture_cap_deg,backward_progress,grid_step_deg, ...
        progress_step,rate_deg_s,cache)
%R4_EVALUATE_SETTING Point scan plus BFS connectivity for one setting.

if nargin<10,cache=[];end
domain=r4_candidate_domain(anchor,model_kind,support_mode, ...
    posture_cap_deg,backward_progress,grid_step_deg,progress_step,cache);
graph=r4_graph_search(domain,anchor,model_kind,support_mode,rate_deg_s);
goals=find(domain.is_goal);
if isempty(goals)
    nearest=NaN;nearest_q=[NaN;NaN];nearest_s=NaN;
else
    distances=vecnorm(rad2deg(domain.q_rad(:,goals)-anchor.q_rad),2,1);
    [nearest,which]=min(distances);idx=goals(which);
    nearest_q=domain.q_rad(:,idx);nearest_s=domain.s(idx);
end
evaluation=struct('anchor_id',anchor.anchor_id,'case_name',anchor.case_name, ...
    'role',anchor.role,'model_kind',string(model_kind), ...
    'support_mode',string(support_mode),'family',string(family), ...
    'posture_cap_deg',posture_cap_deg, ...
    'backward_progress',backward_progress,'grid_step_deg',grid_step_deg, ...
    'progress_step',progress_step,'rate_deg_s',rate_deg_s, ...
    'point_count',numel(domain.s),'feasible_point_count',numel(goals), ...
    'transit_point_count',sum(domain.is_transit), ...
    'nearest_feasible_distance_deg',nearest, ...
    'nearest_feasible_q_rad',nearest_q,'nearest_feasible_s',nearest_s, ...
    'classification',graph.classification,'connected',graph.connected, ...
    'seed_count',graph.seed_count,'visited_count',graph.visited_count, ...
    'path_q_rad',graph.path_q_rad,'path_s',graph.path_s, ...
    'minimum_path_force_margin_N',graph.minimum_force_margin_N, ...
    'maximum_path_residual_Nm',graph.maximum_residual_Nm);
end
