function edge = r4_local_edge_feasibility(q_from,q_to,anchor, ...
        model_kind,support_mode,rate_deg_s)
%R4_LOCAL_EDGE_FEASIBILITY Local nonzero-rate dynamic edge predicate.

delta=q_to(:)-q_from(:);max_delta=max(abs(rad2deg(delta)));
local=max_delta<=1.5+1e-12 && max_delta>1e-9;
duration=max_delta/rate_deg_s;
if ~local
    edge=struct('feasible',false,'duration_s',NaN,'rate_deg_s',rate_deg_s, ...
        'residual_norm_Nm',Inf,'force_margin_N',-Inf);return;
end
dq=delta/duration;q_mid=(q_from(:)+q_to(:))/2;
diagnostic=r4_balance_diagnostic(q_mid,dq,zeros(2,1),anchor, ...
    model_kind,support_mode);
c=anchor.config;model=r4_model_parameters(anchor,model_kind);
lower=model.q_min+model.soft_limit_margin;
upper=model.q_max-model.soft_limit_margin;
clearance=min([q_from(:),q_mid,q_to(:)]-lower, ...
    upper-[q_from(:),q_mid,q_to(:)]);
geometry_ok=all(clearance(:)>=-c.soft_margin_tolerance_rad);
bed_ok=string(support_mode)=="robot_only" || ...
    diagnostic.bed.total_normal_force_N>=c.contact_force_threshold_N;
force_ok=diagnostic.exact_feasible && ...
    all(abs(diagnostic.exact_force_N)<=c.force_bound_N+c.bound_tolerance_N);
residual_ok=diagnostic.bounded_residual_norm_Nm<= ...
    c.dynamic_residual_tolerance_Nm;
soft_ok=~any(diagnostic.passive.soft.active);
edge=struct('feasible',local&&geometry_ok&&bed_ok&&force_ok&&residual_ok&&soft_ok, ...
    'duration_s',duration,'rate_deg_s',rate_deg_s, ...
    'residual_norm_Nm',diagnostic.bounded_residual_norm_Nm, ...
    'force_margin_N',diagnostic.force_margin_N,'geometry_ok',geometry_ok, ...
    'bed_ok',bed_ok,'force_ok',force_ok,'residual_ok',residual_ok, ...
    'soft_ok',soft_ok);
end
