function point = r4_point_feasibility(q,anchor,model_kind,support_mode)
%R4_POINT_FEASIBILITY R3C-compatible static recovery-point predicate.

q=q(:); c=anchor.config; p=r4_model_parameters(anchor,model_kind);
lower=p.q_min+p.soft_limit_margin;
upper=p.q_max-p.soft_limit_margin;
rom_ok=all(q>=p.q_min-c.rom_tolerance_rad & ...
    q<=p.q_max+c.rom_tolerance_rad);
soft_clearance=min(q-lower,upper-q);
soft_ok=all(soft_clearance>=-c.soft_margin_tolerance_rad);
resume_ok=soft_clearance(2)>=c.r3c_resume_buffer_rad;
if rom_ok
    balance=r4_balance_diagnostic(q,zeros(2,1),zeros(2,1), ...
        anchor,model_kind,support_mode);
    bed_ok=string(support_mode)=="robot_only" || ...
        balance.bed.total_normal_force_N>=c.contact_force_threshold_N;
    soft_torque_ok=~any(balance.passive.soft.active);
    force_ok=balance.exact_feasible && ...
        all(abs(balance.exact_force_N)<=c.force_bound_N+c.bound_tolerance_N);
    residual_ok=balance.bounded_residual_norm_Nm<= ...
        c.dynamic_residual_tolerance_Nm;
    horizon=c.r3c_prediction_horizon_s;
    ddq_pred=balance.model_parameters.q_min*0;
    if all(isfinite(balance.bounded_force_N))
        [M,h,~,G]=human_two_link_v2_dynamics_terms(q,zeros(2,1), ...
            balance.model_parameters);
        tau_passive=human_two_link_v2_passive_torque(q,zeros(2,1), ...
            balance.model_parameters);
        ddq_pred=M\(balance.mapping.A*balance.bounded_force_N+ ...
            balance.tau_bed_Nm-h-G-tau_passive);
    end
    q_pred=q+0.5*ddq_pred*horizon^2;
    predicted_clearance=min(q_pred-lower,upper-q_pred);
    horizon_hold_ok=all(predicted_clearance>=-c.soft_margin_tolerance_rad) && ...
        predicted_clearance(2)>=c.r3c_hold_buffer_rad;
    horizon_ok=all(predicted_clearance>=-c.soft_margin_tolerance_rad) && ...
        predicted_clearance(2)>=c.r3c_resume_buffer_rad;
else
    balance=struct('bed',struct('total_normal_force_N',NaN), ...
        'exact_force_N',[NaN;NaN],'bounded_force_N',[NaN;NaN], ...
        'force_margin_N',-Inf,'bounded_residual_norm_Nm',Inf, ...
        'mapping',struct('sigma_min',NaN,'condition_number',Inf), ...
        'rank_deficient',true);
    bed_ok=false;soft_torque_ok=false;force_ok=false;residual_ok=false;
    q_pred=[NaN;NaN];predicted_clearance=[-Inf;-Inf];
    horizon_hold_ok=false;horizon_ok=false;
end
transit_feasible=rom_ok && soft_ok && bed_ok && soft_torque_ok && ...
    force_ok && residual_ok && horizon_hold_ok;
feasible=rom_ok && soft_ok && resume_ok && bed_ok && soft_torque_ok && ...
    force_ok && residual_ok && horizon_ok;
point=struct('q_rad',q,'model_kind',string(model_kind), ...
    'support_mode',string(support_mode),'feasible',feasible, ...
    'transit_feasible',transit_feasible, ...
    'rom_ok',rom_ok,'soft_ok',soft_ok,'resume_ok',resume_ok, ...
    'bed_ok',bed_ok,'soft_torque_ok',soft_torque_ok, ...
    'force_ok',force_ok,'residual_ok',residual_ok, ...
    'horizon_hold_ok',horizon_hold_ok,'horizon_ok',horizon_ok, ...
    'soft_clearance_rad',soft_clearance, ...
    'predicted_q_rad',q_pred,'predicted_clearance_rad',predicted_clearance, ...
    'required_force_N',balance.exact_force_N, ...
    'bounded_force_N',balance.bounded_force_N, ...
    'force_margin_N',balance.force_margin_N, ...
    'bounded_residual_norm_Nm',balance.bounded_residual_norm_Nm, ...
    'sigma_min',balance.mapping.sigma_min, ...
    'condition_number',balance.mapping.condition_number, ...
    'bed_force_N',balance.bed.total_normal_force_N, ...
    'rank_deficient',balance.rank_deficient);
end
