function study = r4_run_study(anchors,config)
%R4_RUN_STUDY Deterministic coarse scan, boundary refinement, and BFS.

evaluations=repmat(empty_evaluation(),0,1);
primary=anchors([anchors.primary]);
for anchor_index=1:numel(primary)
    anchor=primary(anchor_index);
    for model_kind=config.model_kinds
        for support_mode=config.support_modes
            cache=containers.Map('KeyType','char','ValueType','any');
            context=[char(anchor.anchor_id),' ',char(model_kind),' ',char(support_mode)];
            fprintf('R4 context %s\n',context);
            % Family A: fixed progress, posture freedom only.
            a_start=numel(evaluations)+1;
            for cap=config.posture_caps_deg
                evaluations(end+1)=tag(r4_evaluate_setting(anchor,model_kind, ...
                    support_mode,"A_POSTURE_ONLY",cap,0, ...
                    config.coarse_posture_step_deg, ...
                    config.coarse_progress_step, ...
                    config.primary_recovery_rate_deg_s,cache),"coarse"); %#ok<AGROW>
            end
            a_rows=evaluations(a_start:end);
            connected=find([a_rows.connected],1);
            if ~isempty(connected)
                if connected==1,lo=0;else,lo=a_rows(connected-1).posture_cap_deg;end
                hi=a_rows(connected).posture_cap_deg;
                for cap=lo+0.5:0.5:hi-0.5
                    evaluations(end+1)=tag(r4_evaluate_setting(anchor,model_kind, ...
                        support_mode,"A_POSTURE_ONLY",cap,0, ...
                        config.refined_posture_step_deg, ...
                        config.coarse_progress_step, ...
                        config.primary_recovery_rate_deg_s,cache),"refined"); %#ok<AGROW>
                end
            elseif is_primary_oracle_context(anchor,model_kind,support_mode)
                cap=max(config.posture_caps_deg);
                evaluations(end+1)=tag(r4_evaluate_setting(anchor,model_kind, ...
                    support_mode,"A_POSTURE_ONLY",cap,0, ...
                    config.refined_posture_step_deg, ...
                    config.refined_progress_step, ...
                    config.primary_recovery_rate_deg_s,cache), ...
                    "refined_no_connection"); %#ok<AGROW>
            end
            % Family B: current 10-degree tube, backward progress only.
            b_start=numel(evaluations)+1;
            for back=config.backward_progress
                evaluations(end+1)=tag(r4_evaluate_setting(anchor,model_kind, ...
                    support_mode,"B_BACKWARD_ONLY",10,back, ...
                    config.coarse_posture_step_deg, ...
                    config.coarse_progress_step, ...
                    config.primary_recovery_rate_deg_s,cache),"coarse"); %#ok<AGROW>
            end
            b_rows=evaluations(b_start:end);connected=find([b_rows.connected],1);
            if ~isempty(connected) && connected>1
                lo=b_rows(connected-1).backward_progress;
                hi=b_rows(connected).backward_progress;
                for back=lo+0.005:0.005:hi-0.005
                    evaluations(end+1)=tag(r4_evaluate_setting(anchor,model_kind, ...
                        support_mode,"B_BACKWARD_ONLY",10,back, ...
                        config.refined_posture_step_deg, ...
                        config.refined_progress_step, ...
                        config.primary_recovery_rate_deg_s,cache),"refined"); %#ok<AGROW>
                end
            elseif isempty(connected) && ...
                    is_primary_oracle_context(anchor,model_kind,support_mode)
                back=max(config.backward_progress);
                evaluations(end+1)=tag(r4_evaluate_setting(anchor,model_kind, ...
                    support_mode,"B_BACKWARD_ONLY",10,back, ...
                    config.refined_posture_step_deg, ...
                    config.refined_progress_step, ...
                    config.primary_recovery_rate_deg_s,cache), ...
                    "refined_no_connection"); %#ok<AGROW>
            end
            % Family C: approved coarse posture/backward Cartesian product.
            c_start=numel(evaluations)+1;
            for cap=config.posture_caps_deg
                for back=config.backward_progress
                    evaluations(end+1)=tag(r4_evaluate_setting(anchor,model_kind, ...
                        support_mode,"C_COMBINED",cap,back, ...
                        config.coarse_posture_step_deg, ...
                        config.coarse_progress_step, ...
                        config.primary_recovery_rate_deg_s,cache),"coarse"); %#ok<AGROW>
                end
            end
            % Refine only the primary moderate-oracle true/bed boundary cell.
            if anchor.case_name=="moderate_oracle" && model_kind=="true" && ...
                    support_mode=="bed_assisted"
                c_rows=evaluations(c_start:end);mask=[c_rows.connected];
                if any(mask)
                    connected_rows=c_rows(mask);
                    score=([connected_rows.posture_cap_deg]/30).^2+ ...
                        ([connected_rows.backward_progress]/0.20).^2;
                    [~,knee]=min(score);base=connected_rows(knee);
                    caps=unique(max(0,base.posture_cap_deg-2):0.5: ...
                        base.posture_cap_deg);
                    backs=unique(max(0,base.backward_progress-0.02):0.005: ...
                        base.backward_progress);
                    for cap=caps
                        for back=backs
                            evaluations(end+1)=tag(r4_evaluate_setting(anchor, ...
                                model_kind,support_mode,"C_COMBINED",cap,back, ...
                                config.refined_posture_step_deg, ...
                                config.refined_progress_step, ...
                                config.primary_recovery_rate_deg_s,cache),"refined"); %#ok<AGROW>
                        end
                    end
                else
                    evaluations(end+1)=tag(r4_evaluate_setting(anchor, ...
                        model_kind,support_mode,"C_COMBINED", ...
                        max(config.posture_caps_deg), ...
                        max(config.backward_progress), ...
                        config.refined_posture_step_deg, ...
                        config.refined_progress_step, ...
                        config.primary_recovery_rate_deg_s,cache), ...
                        "refined_no_connection"); %#ok<AGROW>
                end
            end
        end
    end
end
% HOLD anchors are diagnostic only at the maximum approved combined domain.
holds=anchors(~[anchors.primary]);
for anchor_index=1:numel(holds)
    for model_kind=config.model_kinds
        evaluations(end+1)=tag(r4_evaluate_setting(holds(anchor_index), ...
            model_kind,"bed_assisted","C_COMBINED",30,0.20, ...
            config.coarse_posture_step_deg,config.coarse_progress_step, ...
            config.primary_recovery_rate_deg_s),"hold_diagnostic"); %#ok<AGROW>
    end
end
% Non-near-zero rate sensitivity and 0.25-degree convergence check.
for anchor=reshape(primary([primary.case_name]=="moderate_oracle"),1,[])
    selected=select_best(evaluations,anchor.anchor_id,"true", ...
        "bed_assisted","A_POSTURE_ONLY");
    if isempty(selected)
        selected=select_maximum(evaluations,anchor.anchor_id,"true", ...
            "bed_assisted","A_POSTURE_ONLY");
    end
    for rate=config.recovery_rate_sensitivity_deg_s
        evaluations(end+1)=tag(r4_evaluate_setting(anchor,"true", ...
            "bed_assisted","A_POSTURE_ONLY",selected.posture_cap_deg,0, ...
            config.refined_posture_step_deg,config.refined_progress_step, ...
            rate),"rate_sensitivity"); %#ok<AGROW>
    end
    evaluations(end+1)=tag(r4_evaluate_setting(anchor,"true", ...
        "bed_assisted","A_POSTURE_ONLY",selected.posture_cap_deg,0, ...
        config.convergence_posture_step_deg,config.refined_progress_step, ...
        config.primary_recovery_rate_deg_s),"convergence_0p25deg"); %#ok<AGROW>
end
evaluation_table=r4_evaluation_table(evaluations);
boundary_table=r4_boundary_table(evaluations);
path_table=r4_path_table(evaluations,boundary_table);
study=struct('evaluations',evaluations,'evaluation_table',evaluation_table, ...
    'point_feasibility_summary',evaluation_table, ...
    'recovery_boundary_summary',boundary_table, ...
    'connected_corridor_summary',boundary_table, ...
    'true_vs_perceived_feasibility',r4_true_vs_perceived_table(boundary_table), ...
    'recovery_paths',path_table);
end

function value=tag(value,stage),value.scan_stage=string(stage);end
function value=empty_evaluation()
value=struct('anchor_id',"",'case_name',"",'role',"",'model_kind',"", ...
    'support_mode',"",'family',"",'posture_cap_deg',NaN, ...
    'backward_progress',NaN,'grid_step_deg',NaN,'progress_step',NaN, ...
    'rate_deg_s',NaN,'point_count',0,'feasible_point_count',0, ...
    'transit_point_count',0,'nearest_feasible_distance_deg',NaN, ...
    'nearest_feasible_q_rad',[NaN;NaN],'nearest_feasible_s',NaN, ...
    'classification',"",'connected',false,'seed_count',0, ...
    'visited_count',0,'path_q_rad',zeros(2,0),'path_s',zeros(0,1), ...
    'minimum_path_force_margin_N',NaN,'maximum_path_residual_Nm',NaN, ...
    'scan_stage',"");
end
function selected=select_best(values,anchor_id,model,support,family)
mask=[values.anchor_id]==anchor_id & [values.model_kind]==model & ...
    [values.support_mode]==support & [values.family]==family;
rows=values(mask);connected=rows([rows.connected]);
if isempty(connected),selected=[];return;end
[~,order]=sortrows([[connected.posture_cap_deg]', ...
    [connected.backward_progress]'],[1,2]);selected=connected(order(1));
end
function selected=select_maximum(values,anchor_id,model,support,family)
mask=[values.anchor_id]==anchor_id & [values.model_kind]==model & ...
    [values.support_mode]==support & [values.family]==family;
rows=values(mask);[~,index]=max([rows.posture_cap_deg]+ ...
    100*[rows.backward_progress]);selected=rows(index);
end
function yes=is_primary_oracle_context(anchor,model_kind,support_mode)
yes=anchor.case_name=="moderate_oracle" && model_kind=="true" && ...
    support_mode=="bed_assisted";
end
