function state=r3c_safety_initial_state(initial_reference)
%R3C_SAFETY_INITIAL_STATE Deterministic transparent safety state.

state=struct('mode',"NORMAL",'classification',"RUNNING", ...
    'mode_time_s',0,'alpha',1,'first_intervention_time_s',NaN, ...
    'first_intervention_progress',NaN,'slowdown_count',0, ...
    'hold_count',0,'recovery_count',0,'recovery_success_count',0, ...
    'slowdown_time_s',0,'hold_time_s',0,'recovery_time_s',0, ...
    'total_intervention_time_s',0,'recovery_command_q', ...
    initial_reference(:),'recovery_command_dq',zeros(2,1), ...
    'resume_blending',false, ...
    'last_reason',"NONE");
end
