function row=r3c_case_record(case_name,model_kind,result)
%R3C_CASE_RECORD Common formal R3C task/safety/dynamics/ID metrics.

m=result.metrics;s=m.safety;id=m.identifier;c=result.config;
if s.recovery_count==0,s.max_reference_deviation_deg=0;end
q=result.state(1:2,:);p=result.plant_parameters;force=result.robot_force_N;
row=struct('case_name',string(case_name),'model_kind',string(model_kind), ...
    'classification',string(result.terminal_state),'duration_s',m.duration_s, ...
    'progress',m.final_s,'completion_time_s',m.completion_time_s, ...
    'min_q2_soft_clearance_deg',s.min_q2_soft_clearance_deg, ...
    'min_q1_soft_clearance_deg',s.min_q1_soft_clearance_deg, ...
    'soft_limit_samples',m.soft_limit_active_samples, ...
    'rom_violation_samples',m.rom_violation_samples, ...
    'force_violation_samples',s.force_violation_samples, ...
    'first_intervention_time_s',s.first_intervention_time_s, ...
    'first_intervention_progress',s.first_intervention_progress, ...
    'slowdown_count',s.slowdown_count,'slowdown_time_s',s.slowdown_time_s, ...
    'hold_count',s.hold_count,'hold_time_s',s.hold_time_s, ...
    'recovery_count',s.recovery_count,'recovery_time_s',s.recovery_time_s, ...
    'recovery_success_count',s.recovery_success_count, ...
    'max_reference_deviation_deg',s.max_reference_deviation_deg, ...
    'total_intervention_time_s',s.total_intervention_time_s, ...
    'peak_robot_component_N',max(abs(force),[],'all'), ...
    'peak_robot_force_N',m.peak_force_norm_N, ...
    'peak_force_slew_N_s',m.peak_force_rate_N_s, ...
    'max_bounded_residual_Nm',m.dynamic_residual_max_Nm, ...
    'min_dynamic_margin_N',m.min_predicted_dynamic_margin_N, ...
    'accepted_updates',id.accepted_updates,'rejected_updates',id.rejected_updates, ...
    'solver_failures',id.solver_failures, ...
    'initial_parameter_error',id.initial_normalized_error, ...
    'final_parameter_error',id.final_normalized_error, ...
    'estimator_unchanged',true,'warning_buffer_deg', ...
    rad2deg(c.r3c_warning_buffer_rad),'hold_buffer_deg', ...
    rad2deg(c.r3c_hold_buffer_rad),'resume_buffer_deg', ...
    rad2deg(c.r3c_resume_buffer_rad),'tube_cap_deg',c.tube_cap_deg, ...
    'force_bound_N',c.force_bound_N,'min_rom_margin_deg', ...
    rad2deg(min([q-p.q_min;p.q_max-q],[],'all')), ...
    'state_sequence',strjoin(m.state_sequence," -> "), ...
    'safety_sequence',strjoin(unique_sequence(result.safety_state)," -> "));
end


function sequence=unique_sequence(values)
keep=[true,values(2:end)~=values(1:end-1)];sequence=values(keep);
end
