function state = dynamic_robust_v1_safe_takeover_initial_state(u_applied)
%DYNAMIC_ROBUST_V1_SAFE_TAKEOVER_INITIAL_STATE R1 handover state.
%
% U_APPLIED is the actuator command already present at controller startup.
% It is retained as command history only; no plant parameter or mismatch
% label is stored in this runtime state.

u_applied = u_applied(:);
if numel(u_applied) ~= 2 || any(~isfinite(u_applied))
    error('DynamicRobustV1:InvalidTakeoverInitialForce', ...
        'The initial applied force must contain two finite values.');
end
state = struct('mode', "SAFE_HOLD", 'elapsed_s', 0, ...
    'mode_time_s', 0, 'stable_time_s', 0, ...
    'initial_applied_force_N', u_applied, ...
    'previous_soft_margin_rad', [NaN;NaN], ...
    'previous_margin_velocity_rad_s', [NaN;NaN], ...
    'hold_steps', 0, 'scaled_steps', 0, 'full_steps', 0, ...
    'minimum_lambda', 1, 'tracking_entered', false, ...
    'tracking_time_s', NaN, 'timed_out', false);
end
