function state = dynamic_robust_v1_initial_state()
%DYNAMIC_ROBUST_V1_INITIAL_STATE Public deterministic supervisor state.
state = struct('mode', "BED_SUPPORTED_MOTION", ...
    'classification', "RUNNING", 'mode_time_s', 0, ...
    'entry_guard_time_s', 0, 'contact_stable_time_s', 0, ...
    'recontact_stable_time_s', 0, ...
    'absent_stable_time_s', 0, 'recovery_time_s', 0, ...
    'takeover_time_s', 0, 'takeover_paused', false, 'bed_credit', 1);
end
