function [state,details] = dynamic_robust_v1_adaptive_add_transition( ...
        state, x, u, x_next, sample_index, nominal, h_hip, config, ...
        adaptive, allow_update)
%DYNAMIC_ROBUST_V1_ADAPTIVE_ADD_TRANSITION Buffer and gated NLS update.

if nargin<10,allow_update=true;end
state=dynamic_robust_v1_adaptive_window_append( ...
    state,x,u,x_next,sample_index,adaptive);
attempted=false;accepted=false;solver=empty_solver(state.theta_raw);
if size(state.x,2)<adaptive.minimum_window_size
    state.last_status="BUFFERING";
elseif ~allow_update
    state.last_status="UPDATE_DISABLED";
elseif mod(state.total_transitions,adaptive.update_interval)~=0
    state.last_status="NOT_DUE";
else
    attempted=true;state.solve_attempts=state.solve_attempts+1;
    current_residual=dynamic_robust_v1_adaptive_window_residual( ...
        state.theta_model,state,nominal,h_hip,config);
    current_fit=sqrt(mean(current_residual.^2));
    solver=dynamic_robust_v1_adaptive_solve_window( ...
        state,nominal,h_hip,config,adaptive);
    [state,validation]=dynamic_robust_v1_adaptive_commit_candidate( ...
        state,solver,current_fit,nominal,adaptive,sample_index);
    accepted=validation.accepted;
end
details=struct('attempted',attempted,'accepted',accepted, ...
    'status',state.last_status,'theta_raw',state.theta_raw, ...
    'theta_model',state.theta_model,'fit_rms',state.last_fit_rms, ...
    'current_fit_rms',state.last_current_fit_rms, ...
    'rank',state.last_rank,'condition_number', ...
    state.last_condition_number,'solver',solver, ...
    'solve_time_s',state.last_solve_time_s, ...
    'window_count',size(state.x,2), ...
    'oldest_sample_index',first_or_nan(state.sample_index), ...
    'newest_sample_index',last_or_nan(state.sample_index));
end


function solver=empty_solver(theta)
solver=struct('success',false,'theta',theta,'fit_rms',NaN, ...
    'initial_fit_rms',NaN,'iterations',0,'improved',false,'rank',0, ...
    'condition_number',NaN,'solve_time_s',NaN, ...
    'singular_values',zeros(0,1));
end


function value=first_or_nan(values)
if isempty(values),value=NaN;else,value=values(1);end
end


function value=last_or_nan(values)
if isempty(values),value=NaN;else,value=values(end);end
end
