function human_two_link_v2_validate_parameters(p)
%HUMAN_TWO_LINK_V2_VALIDATE_PARAMETERS Validate V2 patient/model fields.

positive_scalars = {'height_m', 'body_mass_kg', 'L1', 'L2', ...
    'm1', 'm2', 'lc1', 'lc2', 'I1', 'I2', 'g', 'sc', ...
    'soft_limit_margin', 'soft_limit_boundary_torque_Nm', ...
    'soft_limit_damping_Nms_rad', 'soft_limit_numerical_tolerance'};
for field_index = 1:numel(positive_scalars)
    name = positive_scalars{field_index};
    if ~isfield(p, name) || ~isscalar(p.(name)) || ...
            ~isfinite(p.(name)) || p.(name) <= 0
        error('HumanTwoLinkV2:InvalidParameter', ...
            'Parameter %s must be a positive finite scalar.', name);
    end
end

vectors = {'q_rest', 'q_min', 'q_max'};
for field_index = 1:numel(vectors)
    name = vectors{field_index};
    if ~isfield(p, name) || numel(p.(name)) ~= 2 || ...
            any(~isfinite(p.(name)))
        error('HumanTwoLinkV2:InvalidParameter', ...
            'Parameter %s must be a finite 2-vector.', name);
    end
end
if ~isequal(size(p.K_passive), [2, 2]) || ...
        ~isequal(size(p.B_passive), [2, 2]) || ...
        any(~isfinite([p.K_passive(:); p.B_passive(:)])) || ...
        min(eig((p.K_passive+p.K_passive')/2)) < 0 || ...
        min(eig((p.B_passive+p.B_passive')/2)) < 0
    error('HumanTwoLinkV2:InvalidPassiveMatrices', ...
        'Passive stiffness and damping must be finite positive semidefinite.');
end
if any(p.q_min >= p.q_max) || ...
        any(p.q_rest < p.q_min) || any(p.q_rest > p.q_max) || ...
        any(2*p.soft_limit_margin >= p.q_max-p.q_min)
    error('HumanTwoLinkV2:InvalidROM', ...
        'ROM, rest pose, and soft-limit margin are inconsistent.');
end
if p.soft_limit_numerical_tolerance >= p.soft_limit_margin
    error('HumanTwoLinkV2:InvalidROM', ...
        'Soft-limit numerical tolerance must be smaller than its margin.');
end
if p.lc1 > p.L1 || p.lc2 > p.L2 || p.sc > p.L2
    error('HumanTwoLinkV2:InvalidGeometry', ...
        'COM and contact distances must lie on their links.');
end
end
