function state = near_extension_protective_mode_initial_state(direction)
%NEAR_EXTENSION_PROTECTIVE_MODE_INITIAL_STATE Initialize landing or takeoff.

direction = string(direction);
if direction == "landing"
    mode = "NORMAL_REHAB";
elseif direction == "takeoff"
    mode = "BED_START";
else
    error('NearExtensionProtectiveMode:InvalidDirection', ...
        'direction must be landing or takeoff.');
end
state = struct('direction', direction, 'mode', mode, ...
    'patch_active', false, 'patch_start_time_s', NaN, ...
    'patch_q0_rad', nan(2, 1), 'patch_dq0_rad_s', nan(2, 1), ...
    'patch_qf_rad', nan(2, 1), 'patch_dqf_rad_s', nan(2, 1), ...
    'patch_ddqf_rad_s2', nan(2, 1), ...
    'protective_stop_latched', false, ...
    'transition_count', 0);
end
