function evidence = near_extension_protective_mode_q_switch_evidence()
%NEAR_EXTENSION_PROTECTIVE_MODE_Q_SWITCH_EVIDENCE Frozen diagnostic extract.

folder = fileparts(mfilename('fullpath'));
snapshot = readtable(fullfile(folder, 'q_switch_evidence_snapshot.csv'), ...
    'TextType', 'string');
evidence = struct('recommended_q_switch_deg', 30, ...
    'engineering_margin_basis', "approximately 10 N registered reserve", ...
    'not_clinical_threshold', true, 'snapshot', snapshot, ...
    'source_relative_path', string(fullfile('linkage', 'results', 'local', ...
    'bed_supported_load_transfer_v1', ...
    'robust_suspended_feasibility_envelope', 'boundary_details.csv')));
end
