function [rows,summary] = r3a_recontact_diagnostics(result,source_name)
%R3A_RECONTACT_DIAGNOSTICS Reconstruct contact quantities in RECONTACT.

indices=find(result.mode=="RECONTACT");
if isempty(indices)
    rows=empty_rows();
    summary=struct('source',string(source_name),'reached',false, ...
        'start_time_s',NaN,'end_time_s',NaN,'logged_span_s',NaN, ...
        'sample_count',0,'any_penetration_contact',false, ...
        'any_force_threshold_contact',false,'active_transitions',0, ...
        'threshold_transitions',0,'maximum_continuous_threshold_s',0, ...
        'final_min_gap_m',NaN,'final_gap_velocity_m_s',NaN, ...
        'final_bed_force_N',NaN,'final_parameter_error',NaN);return;
end
n=numel(indices);source=repmat(string(source_name),n,1);
time_s=result.t(indices)';relative_time_s=(result.t(indices)-result.t(indices(1)))';
min_gap_m=zeros(n,1);closest_gap_velocity_m_s=zeros(n,1);
max_penetration_m=zeros(n,1);total_bed_force_N=zeros(n,1);
active_contact_count=zeros(n,1);
for item=1:n
    index=indices(item);q=result.state(1:2,index);dq=result.state(3:4,index);
    bed=bed_supported_v1_contact(q,dq,result.h_hip_m, ...
        result.plant_parameters,result.config);
    [min_gap_m(item),closest]=min(bed.gap_m);
    closest_gap_velocity_m_s(item)=bed.points.velocity_world(2,closest);
    max_penetration_m(item)=max(bed.penetration_m);
    total_bed_force_N(item)=bed.total_normal_force_N;
    active_contact_count(item)=sum(bed.active);
end
force_threshold_contact=total_bed_force_N>= ...
    result.config.contact_force_threshold_N;
parameter_error=nan(n,1);
adaptive_enabled=isfield(result,'adaptive_enabled') && result.adaptive_enabled;
if adaptive_enabled
    truth=dynamic_robust_v1_adaptive_theta_from_parameters( ...
        result.nominal_parameters,result.plant_parameters);
    range=result.adaptive_config.theta_range;
    for item=1:n
        parameter_error(item)=norm(( ...
            result.identifier_theta_model(:,indices(item))-truth)./range);
    end
elseif isfield(result,'controller_model_parameters') && ...
        isequaln(result.controller_model_parameters,result.plant_parameters)
    parameter_error(:)=0;
end
q1_deg=rad2deg(result.state(1,indices))';
q2_deg=rad2deg(result.state(2,indices))';
dq1_deg_s=rad2deg(result.state(3,indices))';
dq2_deg_s=rad2deg(result.state(4,indices))';
q1_ref_deg=rad2deg(result.q_ref(1,indices))';
q2_ref_deg=rad2deg(result.q_ref(2,indices))';
q1_governed_deg=rad2deg(result.q_nominal(1,indices))';
q2_governed_deg=rad2deg(result.q_nominal(2,indices))';
progress=result.task_s(indices)';
robot_force_norm_N=vecnorm(result.robot_force_N(:,indices),2,1)';
robust_static_margin_N=result.robust_static_margin_N(indices)';
dynamic_margin_N=result.dynamic_margin_N(indices)';
hybrid_mode=result.mode(indices)';
rows=table(source,time_s,relative_time_s,min_gap_m, ...
    closest_gap_velocity_m_s,max_penetration_m,total_bed_force_N, ...
    active_contact_count,force_threshold_contact,q1_deg,q2_deg, ...
    dq1_deg_s,dq2_deg_s,q1_ref_deg,q2_ref_deg,q1_governed_deg, ...
    q2_governed_deg,progress,robot_force_norm_N, ...
    robust_static_margin_N,dynamic_margin_N,parameter_error,hybrid_mode);
active=active_contact_count>0;
summary=struct('source',string(source_name),'reached',true, ...
    'start_time_s',time_s(1),'end_time_s',time_s(end), ...
    'logged_span_s',time_s(end)-time_s(1), ...
    'sample_count',n,'any_penetration_contact',any(active), ...
    'any_force_threshold_contact',any(force_threshold_contact), ...
    'active_transitions',sum(active(2:end)~=active(1:end-1)), ...
    'threshold_transitions',sum(force_threshold_contact(2:end)~= ...
        force_threshold_contact(1:end-1)), ...
    'maximum_continuous_threshold_s',longest_true_run( ...
        force_threshold_contact)*result.config.dt, ...
    'final_min_gap_m',min_gap_m(end), ...
    'final_gap_velocity_m_s',closest_gap_velocity_m_s(end), ...
    'final_bed_force_N',total_bed_force_N(end), ...
    'final_parameter_error',parameter_error(end));
end


function count=longest_true_run(values)
values=logical(values(:));count=0;current=0;
for index=1:numel(values)
    if values(index),current=current+1;count=max(count,current);
    else,current=0;end
end
end


function rows=empty_rows()
rows=table(strings(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),false(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),strings(0,1), ...
    'VariableNames',{'source','time_s','relative_time_s','min_gap_m', ...
    'closest_gap_velocity_m_s','max_penetration_m','total_bed_force_N', ...
    'active_contact_count','force_threshold_contact','q1_deg','q2_deg', ...
    'dq1_deg_s','dq2_deg_s','q1_ref_deg','q2_ref_deg', ...
    'q1_governed_deg','q2_governed_deg','progress', ...
    'robot_force_norm_N','robust_static_margin_N','dynamic_margin_N', ...
    'parameter_error','hybrid_mode'});
end
