function alignment = r3a_tracking_alignment(result)
%R3A_TRACKING_ALIGNMENT Tracking-relative coordinates for logged comparison.

entry=find(result.takeover_mode=="TRACKING",1,'first');
if isempty(entry),error('R3A:TrackingAbsent','Result never enters TRACKING.');end
indices=entry:numel(result.t);
soft_lower=result.plant_parameters.q_min+ ...
    result.plant_parameters.soft_limit_margin;
alignment=struct('entry_index',entry,'indices',indices, ...
    'time_s',result.t(indices)-result.t(entry), ...
    'absolute_time_s',result.t(indices), ...
    'q_deg',rad2deg(result.state(1:2,indices)), ...
    'q_ref_deg',rad2deg(result.q_ref(:,indices)), ...
    'q_nominal_deg',rad2deg(result.q_nominal(:,indices)), ...
    'q2_soft_clearance_deg',rad2deg( ...
        result.state(2,indices)-soft_lower(2)), ...
    'progress',result.task_s(indices), ...
    'force_norm_N',vecnorm(result.robot_force_N(:,indices),2,1), ...
    'bed_force_N',result.bed_force_N(indices), ...
    'inside_tube',result.inside_tube(indices), ...
    'mode',result.mode(indices));
outside=find(~alignment.inside_tube,1,'first');
if isempty(outside),alignment.first_outside_index=NaN;
else,alignment.first_outside_index=indices(outside);end
end
